build_from:
  armhf: "ghcr.io/hassio-addons/base:17.2.3"
  armv7: "ghcr.io/hassio-addons/base:17.2.3"
  aarch64: "ghcr.io/hassio-addons/base:17.2.3"
  amd64: "ghcr.io/hassio-addons/base:17.2.3"
  i386: "ghcr.io/hassio-addons/base:17.2.3"
