#!/usr/bin/env bashio

# <ADDON_BANNER_INJECTION>

# ============================================================================
# Addon Startup Banner - Auto-generated by CI
# ============================================================================
_show_startup_banner() {
	local VERSION="${ADDON_VERSION:-2.0.0}"
	local NAME="Bash Script Executer"
	local SLUG="bashscriptexecuter"
	local UNSUPPORTED="false"
	local REPO="FaserF/hassio-addons"
	local MAINTAINER="FaserF"

	# Extract base version and commit from dev versions (1.2.3-dev+abc123)
	local BASE_VERSION="${VERSION%%-dev*}"
	local DEV_COMMIT=""
	if [[ "$VERSION" == *"+"* ]]; then
		DEV_COMMIT="${VERSION##*+}"
	fi

	# Header
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.blue "  🏠 $NAME"
	bashio::log.blue "  📦 Version: $VERSION"
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

	# Status indicator
	if [ "$UNSUPPORTED" = "true" ]; then
		bashio::log.error "🚨 STATUS: UNSUPPORTED"
		bashio::log.error "   This addon is no longer maintained!"
	elif [[ "$VERSION" == *"-dev"* ]]; then
		bashio::log.warning "🚧 STATUS: DEVELOPMENT"
		bashio::log.warning "   This is a development build!"
	elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
		bashio::log.notice "🔬 STATUS: BETA"
		bashio::log.notice "   This addon is in beta testing."
	else
		bashio::log.green "✅ STATUS: STABLE"
	fi

	# Helper for semantic version comparison
	version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }

	# ========================================================================
	# Smart Update Check
	# ========================================================================
	if command -v curl &>/dev/null; then
		local UPDATE_MSG=""

		# Get latest stable version from config.yaml
		local LATEST_STABLE
		LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//' || true)

		if [ -n "$LATEST_STABLE" ]; then
			# For DEV versions: Check if there are newer commits for this addon
			if [[ "$VERSION" == *"-dev"* ]]; then
				if [ -n "$DEV_COMMIT" ]; then
					# Get latest commit for this addon from GitHub
					local LATEST_COMMIT
					LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7 || true)

					if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
						UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
						bashio::log.yellow "   Your commit: $DEV_COMMIT"
						bashio::log.yellow "   Latest: $LATEST_COMMIT"
					fi
				fi

				# Also check if a stable release is available
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# Compare versions
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
						bashio::log.yellow "   Consider upgrading to the stable release"
					fi
				fi

			# For BETA versions (< 1.0.0): Check for newer beta OR stable
			elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# If stable is >= 1.0.0, it's definitely newer
					local LATEST_MAJOR="${LATEST_STABLE%%.*}"
					if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
					elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi

			# For STABLE versions: Simple version comparison
			else
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi
			fi
		fi

		if [ -n "$UPDATE_MSG" ]; then
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
			bashio::log.yellow "$UPDATE_MSG"
			bashio::log.yellow "   You are running: $VERSION"
			bashio::log.yellow "   Update via the Add-on Store"
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
		fi
	fi

	# Footer with links
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info "📝 Issues: https://github.com/$REPO/issues"
	bashio::log.info "💖 Maintained by: $MAINTAINER"
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue &>/dev/null 2>&1; then
	_show_startup_banner
fi

# </ADDON_BANNER_INJECTION>

# Enable strict mode
set -euo pipefail
# shellcheck disable=SC1091

script_path=$(bashio::config 'script_path')
script_argument1=$(bashio::config 'script_argument1')
script_argument2=$(bashio::config 'script_argument2')
script_argument3=$(bashio::config 'script_argument3')
script_path2=$(bashio::config 'script_path2')
script2_argument1=$(bashio::config 'script2_argument1')
script2_argument2=$(bashio::config 'script2_argument2')
script2_argument3=$(bashio::config 'script2_argument3')
script_path3=$(bashio::config 'script_path3')
script3_argument1=$(bashio::config 'script3_argument1')
script3_argument2=$(bashio::config 'script3_argument2')
script3_argument3=$(bashio::config 'script3_argument3')

if [ "$script_path" != "false" ]; then
	if [ ! -f "$script_path" ]; then
		bashio::log.error "Cannot find your first script at $script_path"
		bashio::log.error "Exiting now..."
		exit 1
	fi
fi

if [ "$script_path2" != "false" ]; then
	if [ ! -f "$script_path2" ]; then
		bashio::log.error "Cannot find your second script at $script_path2"
		bashio::log.error "Exiting now..."
		exit 1
	fi
fi

if [ "$script_path3" != "false" ]; then
	if [ ! -f "$script_path3" ]; then
		bashio::log.error "Cannot find your third script at $script_path3"
		bashio::log.error "Exiting now..."
		exit 1
	fi
fi

#Set 711 rights to script
bashio::log.info "Fixing permissions."
if [ "$script_path" != "false" ]; then
	chmod 711 "$script_path"
fi
if [ "$script_path2" != "false" ]; then
	chmod 711 "$script_path2"
fi
if [ "$script_path3" != "false" ]; then
	chmod 711 "$script_path3"
fi

# Function to execute script with filtered arguments
execute_script() {
	local path="$1"
	local arg1="$2"
	local arg2="$3"
	local arg3="$4"
	local num="$5"

	local args=()
	# Only add argument if it's not empty, 'false', or 'null'
	[[ -n "$arg1" && "$arg1" != "false" && "$arg1" != "null" ]] && args+=("$arg1")
	[[ -n "$arg2" && "$arg2" != "false" && "$arg2" != "null" ]] && args+=("$arg2")
	[[ -n "$arg3" && "$arg3" != "false" && "$arg3" != "null" ]] && args+=("$arg3")

	bashio::log.info "Executing script #$num: $path with ${#args[@]} arguments..."
	bashio::log.info "-----------------------------------------------------------"
	bash "$path" "${args[@]}"
}

if [ "$script_path" != "false" ]; then
	execute_script "$script_path" "$script_argument1" "$script_argument2" "$script_argument3" "1"
fi

if [ "$script_path2" != "false" ]; then
	execute_script "$script_path2" "$script2_argument1" "$script2_argument2" "$script2_argument3" "2"
fi

if [ "$script_path3" != "false" ]; then
	execute_script "$script_path3" "$script3_argument1" "$script3_argument2" "$script3_argument3" "3"
fi

bashio::log.info "-----------------------------------------------------------"
bashio::log.info "All Scripts were executed. Stopping container..."
