# .github/labeler.yml
# Add 'core' label for root repo changes
core:
- any: ['*', '.github/**']

# Add specific labels for add-ons logic
addon/config:
- changed-files:
    - any-glob-to-any-file: '**/config.yaml'
    - any-glob-to-any-file: '**/config.json'

addon/docker:
- changed-files:
    - any-glob-to-any-file: '**/Dockerfile'

# Specific add-on labels (examples, would need generation for all)
addon: whatsapp:
- changed-files:
    - any-glob-to-any-file: 'whatsapp/**'
