#
# Those are the addon path filters used in the workflows to determine which addon needs to be build.
apache2-minimal-mariadb: apache2-minimal-mariadb/**
apache2-minimal: apache2-minimal/**
apache2: apache2/**
bash_script_executer: bash_script_executer/**
matterbridge: matterbridge/**
netboot-xyz: netboot-xyz/**
openssl: openssl/**
pterodactyl-panel: pterodactyl-panel/**
pterodactyl-wings: pterodactyl-wings/**
switch_lan_play: switch_lan_play/**
switch_lan_play_server: switch_lan_play_server/**
tado_aa: tado_aa/**
