#
# Those are the addon path filters used in the workflows to determine which
# addon needs to be build.
---
ShieldDNS: ShieldDNS/**
apache2-minimal-mariadb: apache2-minimal-mariadb/**
apache2-minimal: apache2-minimal/** # Image : yes
apache2: apache2/** # Image : yes
bash_script_executer: bash_script_executer/** # Image : yes
bt-mqtt-gateway: bt-mqtt-gateway/**
freenom-dns-updater: freenom-dns-updater/**
matterbridge: matterbridge/** # Image : yes
netboot-xyz: netboot-xyz/** # Image : yes
openssl: openssl/** # Image : yes
pterodactyl-panel: pterodactyl-panel/** # Image : yes
pterodactyl-wings: pterodactyl-wings/** # Image : yes
solumati: solumati/** # Image : yes
switch_lan_play: switch_lan_play/** # Image : yes
switch_lan_play_server: switch_lan_play_server/**
tado_aa: tado_aa/** # Image : yes
tuya-convert: tuya-convert/**
wiki.js: wiki.js/**
xqrepack: xqrepack/**
