default: true
MD013: false
line-length: false
MD024:
  siblings_only: true
MD033:
  allowed_elements:
    - img
    - a
    - div
    - h1
    - p
    - table
    - thead
    - tr
    - th
    - tbody
    - td
    - strong
    - br
    - svg
    - path
    - span
    - details
    - summary
MD025: false # Allow frontmatter title + H1 if needed, or just handle manually
