[mypy]
python_version = 3.14
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_calls = False
warn_return_any = False
warn_unused_configs = True
disable_error_code = import-not-found

[mypy-homeassistant.*]
ignore_missing_imports = True

[mypy-voluptuous.*]
ignore_missing_imports = True

[mypy-aiohttp.*]
ignore_missing_imports = True

[mypy-async_timeout.*]
ignore_missing_imports = True
