import fs from 'fs';
import { loadTelegramStore, saveTelegramStore, updateCachedChat } from './store.js';
import { getTelegramBotClient } from './bot.js';
import { recordMessageMap, resolveWaMsgFromTg, resolveTgMsgFromWa } from './message_map.js';
import { waToTelegramHtml, anonymizePhoneNumber } from './format.js';
import { applyRegexReplacements } from './regex.js';
import { logger } from '../../logger.js';
import { getSession, sessions } from '../../session.js';

let pollingTimer = null;

export function formatHeader(
  sourceGroup,
  senderName,
  includeGroup,
  includeSender,
  anonymizePhone = false
) {
  const parts = [];
  if (includeGroup && sourceGroup) {
    const cleanGroup = String(sourceGroup).endsWith('@g.us')
      ? `Group ${sourceGroup.split('@')[0]}`
      : sourceGroup;
    parts.push(cleanGroup);
  }
  if (includeSender && senderName) {
    const displayName = anonymizePhone ? anonymizePhoneNumber(senderName) : senderName;
    parts.push(displayName);
  }
  if (parts.length === 0) return '';
  return `<b>[${parts.join(' | ')}]</b>:\n`;
}

export async function syncWhatsAppToTelegram(
  msg,
  waJid,
  groupName,
  senderName,
  textContent,
  mediaUrl = null,
  mediaPath = null,
  mediaType = null
) {
  const store = loadTelegramStore();
  if (!store.enabled || !store.bot_token) return;

  // Find active mappings for this WhatsApp JID
  const mappings = (store.mappings || []).filter(
    (m) =>
      m.enabled &&
      m.wa_jid === waJid &&
      (m.sync_mode === 'bidirectional' || m.sync_mode === 'outbound')
  );

  if (mappings.length === 0) return;

  const waMsgId = msg.key?.id;
  if (waMsgId) {
    const isBotEcho = resolveTgMsgFromWa(waMsgId);
    if (isBotEcho) return; // Prevent loop echo of messages generated by Telegram bot
  }

  const contextInfo =
    msg.message?.extendedTextMessage?.contextInfo ||
    msg.message?.imageMessage?.contextInfo ||
    msg.message?.videoMessage?.contextInfo ||
    msg.message?.documentMessage?.contextInfo ||
    msg.message?.audioMessage?.contextInfo;
  const quotedWaId = contextInfo?.stanzaId;
  let replyToTgMsgId = null;
  let quotedTextFallback = '';
  if (quotedWaId) {
    const mapRecord = resolveTgMsgFromWa(quotedWaId);
    if (mapRecord) {
      replyToTgMsgId = mapRecord.tgMsgId;
    } else {
      // Fallback: If original WA message is missing from mapping cache, extract quote snippet
      const qText =
        contextInfo?.quotedMessage?.conversation ||
        contextInfo?.quotedMessage?.extendedTextMessage?.text ||
        contextInfo?.quotedMessage?.imageMessage?.caption ||
        '';
      const qParticipant = contextInfo?.participant ? contextInfo.participant.split('@')[0] : '';
      if (qText || qParticipant) {
        const qSender = qParticipant ? `<b>${qParticipant}</b>: ` : '';
        const snippet = qText ? (qText.length > 80 ? `${qText.substring(0, 80)}...` : qText) : '';
        quotedTextFallback = `<blockquote>${qSender}${waToTelegramHtml(snippet)}</blockquote>\n`;
      }
    }
  }

  const reactionObj = msg.message?.reactionMessage;
  if (reactionObj) {
    const targetWaMsgId = reactionObj.key?.id;
    const emoji = reactionObj.text || '';
    if (targetWaMsgId) {
      const mappedRecord = resolveTgMsgFromWa(targetWaMsgId);
      if (mappedRecord && mappedRecord.tgMsgId) {
        for (const mapping of mappings) {
          if (mapping.sync_reactions !== false) {
            const bot = getTelegramBotClient(mapping.bot_id);
            if (bot) {
              bot
                .setMessageReaction(mapping.tg_chat_id, mappedRecord.tgMsgId, emoji)
                .catch((err) => {
                  logger.warn({ error: err.message }, '⚠️ Failed to sync reaction to Telegram');
                });
            }
          }
        }
      }
    }
    return; // Reactions handled, do not send as a text message
  }

  const isFromMe = Boolean(msg.key?.fromMe);

  for (const mapping of mappings) {
    if (isFromMe && !mapping.sync_self_messages) {
      continue;
    }
    const bot = getTelegramBotClient(mapping.bot_id);
    if (!bot) continue;
    if (mapping.ignore_command_prefixes && textContent) {
      const cleanText = textContent.trim();
      const prefixes = String(mapping.ignore_command_prefixes)
        .split(/[,;\s]+/)
        .map((s) => s.trim())
        .filter(Boolean);
      if (prefixes.some((p) => cleanText.startsWith(p))) {
        continue;
      }
    }
    try {
      const isGroupWa = waJid.endsWith('@g.us');
      const isDirectMirror = Boolean(mapping.is_direct_chat_mirror);
      const header = isDirectMirror
        ? ''
        : formatHeader(
            groupName,
            senderName,
            isGroupWa ? mapping.include_group_name : false,
            isGroupWa ? mapping.include_sender_name : false,
            mapping.anonymize_phone_numbers
          );

      let processedText = applyRegexReplacements(textContent, mapping.regex_replacements || []);
      const formattedBody =
        mapping.convert_formatting !== false
          ? waToTelegramHtml(processedText)
          : processedText || '';
      const fullText = `${header}${quotedTextFallback}${formattedBody}`;

      const silent = Boolean(mapping.silent_delivery);
      const threadId = mapping.tg_thread_id || null;

      let tgResult = null;
      const mediaSource = (mediaPath && fs.existsSync(mediaPath)) ? mediaPath : mediaUrl;
      if (mediaSource) {
        if (mediaType === 'sticker') {
          tgResult = await bot.sendMediaFile('sendSticker', mapping.tg_chat_id, mediaSource, 'sticker', '', replyToTgMsgId, threadId, silent).catch(() => null);
        } else if (mediaType === 'image') {
          tgResult = await bot.sendMediaFile('sendPhoto', mapping.tg_chat_id, mediaSource, 'photo', fullText, replyToTgMsgId, threadId, silent).catch(() => null);
        } else if (mediaType === 'video') {
          tgResult = await bot.sendMediaFile('sendVideo', mapping.tg_chat_id, mediaSource, 'video', fullText, replyToTgMsgId, threadId, silent).catch(() => null);
        } else if (mediaType === 'audio') {
          tgResult = await bot.sendMediaFile('sendVoice', mapping.tg_chat_id, mediaSource, 'voice', fullText, replyToTgMsgId, threadId, silent).catch(() => null);
        } else if (mediaType === 'document') {
          tgResult = await bot.sendMediaFile('sendDocument', mapping.tg_chat_id, mediaSource, 'document', fullText, replyToTgMsgId, threadId, silent).catch(() => null);
        }

        if (!tgResult) {
          tgResult = await bot.sendMediaFile('sendPhoto', mapping.tg_chat_id, mediaSource, 'photo', fullText, replyToTgMsgId, threadId, silent)
            .catch(() => bot.sendMediaFile('sendDocument', mapping.tg_chat_id, mediaSource, 'document', fullText, replyToTgMsgId, threadId, silent))
            .catch(() => {
              const mediaFallbackText = `${fullText}\n<i>[Media File Attached]</i>`;
              return bot.sendMessage(mapping.tg_chat_id, mediaFallbackText, replyToTgMsgId, threadId, silent);
            });
        }
      } else {
        tgResult = await bot.sendMessage(mapping.tg_chat_id, fullText, replyToTgMsgId, threadId, silent);
      }

      if (tgResult && tgResult.message_id && waMsgId) {
        recordMessageMap(
          waMsgId,
          mapping.tg_chat_id,
          tgResult.message_id,
          waJid,
          isFromMe,
          senderName
        );
      }
    } catch (err) {
      logger.error(
        { error: err.message, waJid, tgChatId: mapping.tg_chat_id },
        '❌ Error syncing WA message to Telegram'
      );
    }
  }
}

const lastUpdateIds = new Map();

export async function processTelegramUpdates() {
  const store = loadTelegramStore();
  if (!store.enabled) return;

  const bots = (store.bots || []).filter((b) => b.enabled && b.token);
  if (bots.length === 0) return;

  for (const botConfig of bots) {
    const bot = getTelegramBotClient(botConfig.id);
    if (!bot) continue;

    let lastUpdateId = lastUpdateIds.get(botConfig.id) || 0;

    try {
      const updates = await bot.request('getUpdates', {
        offset: lastUpdateId + 1,
        limit: 50,
        timeout: 0,
        allowed_updates: [
          'message',
          'edited_message',
          'channel_post',
          'edited_channel_post',
          'message_reaction',
          'message_reaction_count',
          'poll',
          'poll_answer',
        ],
      });

      if (!Array.isArray(updates) || updates.length === 0) continue;

      for (const update of updates) {
        lastUpdateId = Math.max(lastUpdateId, update.update_id);
        lastUpdateIds.set(botConfig.id, lastUpdateId);

        // Handle Telegram Poll Answers (when a user votes or changes vote in a poll)
        if (update.poll_answer) {
          const pa = update.poll_answer;
          const pollId = String(pa.poll_id);
          const voterName = pa.user
            ? `${pa.user.first_name || ''} ${pa.user.last_name || ''}`.trim() ||
              pa.user.username ||
              'Telegram User'
            : 'Telegram User';
          const selectedOptionIds = pa.option_ids || [];

          // Find stored poll details if cached
          const cachedPoll = store.cached_polls?.[pollId];
          const pollQuestion = cachedPoll?.question || 'Poll';
          const pollOptions = cachedPoll?.options || [];
          const selectedText = selectedOptionIds
            .map((idx) => pollOptions[idx] || `Option ${idx + 1}`)
            .join(', ');

          const voteText =
            selectedOptionIds.length > 0
              ? `📊 [Poll Vote Update: ${pollQuestion}]\n👤 Voter: ${voterName}\n🗳️ Vote: ${selectedText}`
              : `📊 [Poll Vote Update: ${pollQuestion}]\n👤 Voter: ${voterName}\n🗳️ Vote: Retracted (No options selected)`;

          const tgChatId = String(pa.voter_chat?.id || cachedPoll?.chat_id || '');
          const mappings = (store.mappings || []).filter(
            (m) =>
              m.enabled &&
              (!tgChatId || String(m.tg_chat_id) === tgChatId) &&
              (!m.bot_id || m.bot_id === botConfig.id) &&
              (m.sync_mode === 'bidirectional' || m.sync_mode === 'inbound')
          );

          for (const mapping of mappings) {
            let session = getSession('default');
            if (!session || !session.sock || !session.isConnected) {
              for (const s of sessions.values()) {
                if (s.sock && s.isConnected) {
                  session = s;
                  break;
                }
              }
            }
            if (session && session.sock && session.isConnected) {
              try {
                await session.sock.sendMessage(mapping.wa_jid, { text: voteText });
              } catch (e) {
                logger.error(
                  { error: e.message },
                  '❌ Failed to sync Telegram poll vote to WhatsApp'
                );
              }
            }
          }
          continue;
        }

        // Handle Telegram Poll Updates (when poll options or total voters change)
        if (update.poll) {
          const p = update.poll;
          const pollId = String(p.id);
          if (!store.cached_polls) store.cached_polls = {};
          store.cached_polls[pollId] = {
            id: pollId,
            question: p.question,
            options: (p.options || []).map((o) => o.text),
            total_voter_count: p.total_voter_count,
            is_closed: p.is_closed,
            chat_id: store.cached_polls[pollId]?.chat_id || '',
          };
          saveTelegramStore(store);
          continue;
        }

        // Handle Telegram Message Reactions (message_reaction updates)
        if (update.message_reaction) {
          const reactObj = update.message_reaction;
          const tgChatId = String(reactObj.chat.id);
          const tgMsgId = String(reactObj.message_id);
          const newReactions = reactObj.new_reaction || [];
          const latestEmoji =
            newReactions.length > 0 ? newReactions[newReactions.length - 1].emoji : '';

          const mappings = (store.mappings || []).filter(
            (m) =>
              m.enabled &&
              String(m.tg_chat_id) === tgChatId &&
              (!m.bot_id || m.bot_id === botConfig.id) &&
              (m.sync_mode === 'bidirectional' || m.sync_mode === 'inbound')
          );

          if (mappings.length > 0) {
            const mapped = resolveWaMsgFromTg(tgChatId, tgMsgId);
            if (mapped && mapped.waMsgId && mapped.waJid) {
              let session = getSession('default');
              if (!session || !session.sock || !session.isConnected) {
                for (const s of sessions.values()) {
                  if (s.sock && s.isConnected) {
                    session = s;
                    break;
                  }
                }
              }
              if (session && session.sock && session.isConnected) {
                try {
                  const reactionKey = {
                    remoteJid: mapped.waJid,
                    id: mapped.waMsgId,
                    fromMe: mapped.fromMe !== undefined ? mapped.fromMe : false,
                  };
                  await session.sock.sendMessage(mapped.waJid, {
                    react: {
                      text: latestEmoji || '', // Empty string removes reaction in Baileys
                      key: reactionKey,
                    },
                  });
                } catch (reactErr) {
                  logger.error(
                    { error: reactErr.message },
                    '❌ Failed to sync Telegram reaction to WhatsApp'
                  );
                }
              }
            }
          }
          continue;
        }

        const msg = update.message || update.channel_post;
        if (!msg || !msg.chat) continue;

        updateCachedChat(msg.chat, botConfig.id);

        const tgChatId = String(msg.chat.id);
        const mappings = (store.mappings || []).filter(
          (m) =>
            m.enabled &&
            String(m.tg_chat_id) === tgChatId &&
            (!m.bot_id || m.bot_id === botConfig.id) &&
            (m.sync_mode === 'bidirectional' || m.sync_mode === 'inbound')
        );

        if (mappings.length === 0) continue;

        const senderName = msg.from
          ? `${msg.from.first_name || ''} ${msg.from.last_name || ''}`.trim() ||
            msg.from.username ||
            'Telegram User'
          : msg.chat.title || 'Telegram';
        let tgText = msg.text || msg.caption || '';
        let mediaPayload = null; // { url, type, mimetype }

        try {
          if (msg.sticker) {
            const emoji = msg.sticker.emoji ? ` ${msg.sticker.emoji}` : '';
            tgText = tgText || `[🎨 Sticker${emoji}]`;
            const fileId = msg.sticker.file_id;
            const fileUrl = await bot.getFileUrl(fileId);
            if (fileUrl) {
              mediaPayload = {
                url: fileUrl,
                type: msg.sticker.is_animated || msg.sticker.is_video ? 'document' : 'image',
                mimetype: msg.sticker.is_video ? 'video/webm' : 'image/webp',
              };
            }
          } else if (msg.animation) {
            tgText = tgText || '[🎞️ GIF]';
            const fileId = msg.animation.file_id;
            const fileUrl = await bot.getFileUrl(fileId);
            if (fileUrl) {
              mediaPayload = {
                url: fileUrl,
                type: 'video',
                mimetype: msg.animation.mime_type || 'video/mp4',
              };
            }
          } else if (msg.photo && Array.isArray(msg.photo) && msg.photo.length > 0) {
            tgText = tgText || '[📷 Photo]';
            const bestPhoto = msg.photo[msg.photo.length - 1];
            const fileUrl = await bot.getFileUrl(bestPhoto.file_id);
            if (fileUrl) {
              mediaPayload = { url: fileUrl, type: 'image', mimetype: 'image/jpeg' };
            }
          } else if (msg.video) {
            tgText = tgText || '[🎥 Video]';
            const fileUrl = await bot.getFileUrl(msg.video.file_id);
            if (fileUrl) {
              mediaPayload = {
                url: fileUrl,
                type: 'video',
                mimetype: msg.video.mime_type || 'video/mp4',
              };
            }
          } else if (msg.voice) {
            tgText = tgText || '[🎤 Voice Note]';
            const fileUrl = await bot.getFileUrl(msg.voice.file_id);
            if (fileUrl) {
              mediaPayload = {
                url: fileUrl,
                type: 'audio',
                mimetype: msg.voice.mime_type || 'audio/ogg',
              };
            }
          } else if (msg.audio) {
            tgText = tgText || '[🎵 Audio]';
            const fileUrl = await bot.getFileUrl(msg.audio.file_id);
            if (fileUrl) {
              mediaPayload = {
                url: fileUrl,
                type: 'audio',
                mimetype: msg.audio.mime_type || 'audio/mp3',
              };
            }
          } else if (msg.document) {
            tgText = tgText || `[📄 Document: ${msg.document.file_name || 'file'}]`;
            const fileUrl = await bot.getFileUrl(msg.document.file_id);
            if (fileUrl) {
              mediaPayload = {
                url: fileUrl,
                type: 'document',
                mimetype: msg.document.mime_type || 'application/octet-stream',
                fileName: msg.document.file_name,
              };
            }
          } else if (msg.poll) {
            const p = msg.poll;
            const pollOptions = (p.options || []).map((o) => o.text);
            const optStr =
              pollOptions.length > 0
                ? `\nOptions:\n${pollOptions.map((o, i) => `  ${i + 1}️⃣ ${o}`).join('\n')}`
                : '';
            tgText = `📊 [Poll: ${p.question || 'Untitled'}]${optStr}`;
            const pollId = String(p.id);
            if (!store.cached_polls) store.cached_polls = {};
            store.cached_polls[pollId] = {
              id: pollId,
              question: p.question,
              options: pollOptions,
              chat_id: tgChatId,
            };
            saveTelegramStore(store);
          }
        } catch (mediaErr) {
          logger.warn({ error: mediaErr.message }, '⚠️ Failed to fetch Telegram file URL');
        }

        if (!tgText && !mediaPayload) continue;

        const replyToTgId = msg.reply_to_message?.message_id;
        let quotedWaMsgId = null;
        let tgQuoteSnippet = '';
        if (replyToTgId) {
          const mapped = resolveWaMsgFromTg(tgChatId, replyToTgId);
          if (mapped) {
            quotedWaMsgId = mapped.waMsgId;
          } else if (msg.reply_to_message) {
            const qMsg = msg.reply_to_message;
            const qSender =
              qMsg.from?.first_name || qMsg.from?.username || qMsg.author_signature || 'User';
            const qText = qMsg.text || qMsg.caption || '';
            const snippet = qText
              ? qText.length > 80
                ? `${qText.substring(0, 80)}...`
                : qText
              : '';
            if (snippet || qSender) {
              tgQuoteSnippet = `> [${qSender}]: ${snippet}\n`;
            }
          }
        }

        for (const mapping of mappings) {
          const isGroupChat = msg.chat.type === 'group' || msg.chat.type === 'supergroup';
          const isDirectMirror = Boolean(mapping.is_direct_chat_mirror);
          const rawHeader = isDirectMirror
            ? ''
            : formatHeader(
                isGroupChat ? msg.chat.title : null,
                senderName,
                mapping.include_group_name,
                isGroupChat ? mapping.include_sender_name : false
              );
          const cleanHeader = rawHeader.replace(/<\/?b>/g, '');
          const outboundWaText = `${cleanHeader}${tgQuoteSnippet}${tgText}`;

          let session = getSession('default');
          if (!session || !session.sock || !session.isConnected) {
            for (const s of sessions.values()) {
              if (s.sock && s.isConnected) {
                session = s;
                break;
              }
            }
          }
          if (session && session.sock && session.isConnected) {
            try {
              const sendOptions = {};
              if (quotedWaMsgId) {
                sendOptions.quoted = { key: { remoteJid: mapping.wa_jid, id: quotedWaMsgId } };
              }

              let waContent = { text: outboundWaText };
              if (mediaPayload && mediaPayload.url) {
                if (mediaPayload.type === 'image') {
                  waContent = { image: { url: mediaPayload.url }, caption: outboundWaText };
                } else if (mediaPayload.type === 'video') {
                  waContent = {
                    video: { url: mediaPayload.url },
                    caption: outboundWaText,
                    gifPlayback: Boolean(msg.animation),
                  };
                } else if (mediaPayload.type === 'audio') {
                  waContent = {
                    audio: { url: mediaPayload.url },
                    mimetype: mediaPayload.mimetype,
                    ptt: Boolean(msg.voice),
                  };
                } else if (mediaPayload.type === 'sticker') {
                  waContent = {
                    sticker: { url: mediaPayload.url },
                  };
                } else if (mediaPayload.type === 'document') {
                  waContent = {
                    document: { url: mediaPayload.url },
                    mimetype: mediaPayload.mimetype,
                    fileName: mediaPayload.fileName || 'file',
                    caption: outboundWaText,
                  };
                }
              }

              const sentWaMsg = await session.sock.sendMessage(
                mapping.wa_jid,
                waContent,
                sendOptions
              );
              if (sentWaMsg && sentWaMsg.key && sentWaMsg.key.id) {
                recordMessageMap(
                  sentWaMsg.key.id,
                  tgChatId,
                  msg.message_id,
                  mapping.wa_jid,
                  true,
                  senderName
                );
              }
            } catch (waErr) {
              logger.error(
                { error: waErr.message, waJid: mapping.wa_jid },
                '❌ Error syncing Telegram message to WhatsApp'
              );
            }
          }
        }
      }
    } catch (err) {
      logger.warn({ error: err.message, botId: botConfig.id }, '⚠️ Error polling Telegram updates');
    }
  }
}

export function startTelegramPolling(intervalMs = 3000) {
  if (pollingTimer) clearInterval(pollingTimer);
  pollingTimer = setInterval(processTelegramUpdates, intervalMs);
}

export function stopTelegramPolling() {
  if (pollingTimer) {
    clearInterval(pollingTimer);
    pollingTimer = null;
  }
}
