import { loadTelegramStore, updateCachedChat } from './store.js';
import { getTelegramBotClient } from './bot.js';
import { recordMessageMap, resolveWaMsgFromTg, resolveTgMsgFromWa } from './message_map.js';
import { waToTelegramHtml, anonymizePhoneNumber } from './format.js';
import { applyRegexReplacements } from './regex.js';
import { logger } from '../../logger.js';
import { getSession, sessions } from '../../session.js';

let pollingTimer = null;
let lastUpdateId = 0;

export function formatHeader(
  sourceGroup,
  senderName,
  includeGroup,
  includeSender,
  anonymizePhone = false
) {
  const parts = [];
  if (includeGroup && sourceGroup) {
    const cleanGroup = String(sourceGroup).endsWith('@g.us')
      ? `Group ${sourceGroup.split('@')[0]}`
      : sourceGroup;
    parts.push(cleanGroup);
  }
  if (includeSender && senderName) {
    const displayName = anonymizePhone ? anonymizePhoneNumber(senderName) : senderName;
    parts.push(displayName);
  }
  if (parts.length === 0) return '';
  return `<b>[${parts.join(' | ')}]</b>:\n`;
}

export async function syncWhatsAppToTelegram(
  msg,
  waJid,
  groupName,
  senderName,
  textContent,
  mediaUrl = null
) {
  const store = loadTelegramStore();
  if (!store.enabled || !store.bot_token) return;

  // Find active mappings for this WhatsApp JID
  const mappings = (store.mappings || []).filter(
    (m) =>
      m.enabled &&
      m.wa_jid === waJid &&
      (m.sync_mode === 'bidirectional' || m.sync_mode === 'outbound')
  );

  if (mappings.length === 0) return;

  const bot = getTelegramBotClient();
  if (!bot) return;

  const waMsgId = msg.key?.id;
  if (waMsgId) {
    const isBotEcho = resolveTgMsgFromWa(waMsgId);
    if (isBotEcho) return; // Prevent loop echo of messages generated by Telegram bot
  }

  const quotedWaId = msg.message?.extendedTextMessage?.contextInfo?.stanzaId;
  let replyToTgMsgId = null;
  if (quotedWaId) {
    const mapRecord = resolveTgMsgFromWa(quotedWaId);
    if (mapRecord) replyToTgMsgId = mapRecord.tgMsgId;
  }

  const reactionObj = msg.message?.reactionMessage;
  if (reactionObj) {
    const targetWaMsgId = reactionObj.key?.id;
    const emoji = reactionObj.text || '';
    if (targetWaMsgId) {
      const mappedRecord = resolveTgMsgFromWa(targetWaMsgId);
      if (mappedRecord && mappedRecord.tgMsgId) {
        for (const mapping of mappings) {
          if (mapping.sync_reactions !== false) {
            bot.setMessageReaction(mapping.tg_chat_id, mappedRecord.tgMsgId, emoji).catch((err) => {
              logger.warn({ error: err.message }, '⚠️ Failed to sync reaction to Telegram');
            });
          }
        }
      }
    }
    return; // Reactions handled, do not send as a text message
  }

  const isFromMe = Boolean(msg.key?.fromMe);

  for (const mapping of mappings) {
    if (isFromMe && !mapping.sync_self_messages) {
      continue;
    }
    if (mapping.ignore_command_prefixes && textContent) {
      const cleanText = textContent.trim();
      const prefixes = String(mapping.ignore_command_prefixes)
        .split(/[,;\s]+/)
        .map((s) => s.trim())
        .filter(Boolean);
      if (prefixes.some((p) => cleanText.startsWith(p))) {
        continue;
      }
    }
    try {
      const isGroupWa = waJid.endsWith('@g.us');
      const header = formatHeader(
        groupName,
        senderName,
        isGroupWa ? mapping.include_group_name : false,
        isGroupWa ? mapping.include_sender_name : false,
        mapping.anonymize_phone_numbers
      );

      let processedText = applyRegexReplacements(textContent, mapping.regex_replacements || []);
      const formattedBody =
        mapping.convert_formatting !== false
          ? waToTelegramHtml(processedText)
          : processedText || '';
      const fullText = `${header}${formattedBody}`;

      const silent = Boolean(mapping.silent_delivery);
      const threadId = mapping.tg_thread_id || null;

      let tgResult = null;
      if (mediaUrl) {
        tgResult = await bot
          .sendPhoto(mapping.tg_chat_id, mediaUrl, fullText, replyToTgMsgId, threadId, silent)
          .catch(() => {
            return bot.sendDocument(
              mapping.tg_chat_id,
              mediaUrl,
              fullText,
              replyToTgMsgId,
              threadId,
              silent
            );
          })
          .catch(() => {
            // If media send fails (e.g. invalid URL or unaccessible host), fallback to text notification
            const mediaFallbackText = `${fullText}\n<i>[Media File Attached]</i>`;
            return bot.sendMessage(
              mapping.tg_chat_id,
              mediaFallbackText,
              replyToTgMsgId,
              threadId,
              silent
            );
          });
      } else {
        tgResult = await bot.sendMessage(
          mapping.tg_chat_id,
          fullText,
          replyToTgMsgId,
          threadId,
          silent
        );
      }

      if (tgResult && tgResult.message_id && waMsgId) {
        recordMessageMap(
          waMsgId,
          mapping.tg_chat_id,
          tgResult.message_id,
          waJid,
          isFromMe,
          senderName
        );
      }
    } catch (err) {
      logger.error(
        { error: err.message, waJid, tgChatId: mapping.tg_chat_id },
        '❌ Error syncing WA message to Telegram'
      );
    }
  }
}

export async function processTelegramUpdates() {
  const store = loadTelegramStore();
  if (!store.enabled || !store.bot_token) return;

  const bot = getTelegramBotClient();
  if (!bot) return;

  try {
    const updates = await bot.request('getUpdates', {
      offset: lastUpdateId + 1,
      limit: 50,
      timeout: 0,
      allowed_updates: [
        'message',
        'edited_message',
        'channel_post',
        'edited_channel_post',
        'message_reaction',
        'message_reaction_count',
      ],
    });

    if (!Array.isArray(updates) || updates.length === 0) return;

    for (const update of updates) {
      lastUpdateId = Math.max(lastUpdateId, update.update_id);

      // Handle Telegram Message Reactions (message_reaction updates)
      if (update.message_reaction) {
        const reactObj = update.message_reaction;
        const tgChatId = String(reactObj.chat.id);
        const tgMsgId = String(reactObj.message_id);
        const newReactions = reactObj.new_reaction || [];
        const latestEmoji =
          newReactions.length > 0 ? newReactions[newReactions.length - 1].emoji : '';

        const mappings = (store.mappings || []).filter(
          (m) =>
            m.enabled &&
            String(m.tg_chat_id) === tgChatId &&
            (m.sync_mode === 'bidirectional' || m.sync_mode === 'inbound')
        );

        if (mappings.length > 0) {
          const mapped = resolveWaMsgFromTg(tgChatId, tgMsgId);
          if (mapped && mapped.waMsgId && mapped.waJid) {
            let session = getSession('default');
            if (!session || !session.sock || !session.isConnected) {
              for (const s of sessions.values()) {
                if (s.sock && s.isConnected) {
                  session = s;
                  break;
                }
              }
            }
            if (session && session.sock && session.isConnected) {
              try {
                const reactionKey = {
                  remoteJid: mapped.waJid,
                  id: mapped.waMsgId,
                  fromMe: mapped.fromMe !== undefined ? mapped.fromMe : false,
                };
                await session.sock.sendMessage(mapped.waJid, {
                  react: {
                    text: latestEmoji || '', // Empty string removes reaction in Baileys
                    key: reactionKey,
                  },
                });
              } catch (reactErr) {
                logger.error(
                  { error: reactErr.message },
                  '❌ Failed to sync Telegram reaction to WhatsApp'
                );
              }
            }
          }
        }
        continue;
      }

      const msg = update.message || update.channel_post;
      if (!msg || !msg.chat) continue;

      updateCachedChat(msg.chat);

      const tgChatId = String(msg.chat.id);
      const mappings = (store.mappings || []).filter(
        (m) =>
          m.enabled &&
          String(m.tg_chat_id) === tgChatId &&
          (m.sync_mode === 'bidirectional' || m.sync_mode === 'inbound')
      );

      if (mappings.length === 0) continue;

      const senderName = msg.from
        ? `${msg.from.first_name || ''} ${msg.from.last_name || ''}`.trim() ||
          msg.from.username ||
          'Telegram User'
        : msg.chat.title || 'Telegram';
      let tgText = msg.text || msg.caption || '';
      if (!tgText) {
        if (msg.voice) tgText = '[🎤 Voice Note]';
        else if (msg.audio) tgText = '[🎵 Audio File]';
        else if (msg.photo) tgText = '[📷 Photo]';
        else if (msg.document) tgText = '[📄 Document]';
        else if (msg.sticker) tgText = '[🎨 Sticker]';
        else if (msg.video) tgText = '[🎥 Video]';
      }
      if (!tgText) continue;

      const replyToTgId = msg.reply_to_message?.message_id;
      let quotedWaMsgId = null;
      if (replyToTgId) {
        const mapped = resolveWaMsgFromTg(tgChatId, replyToTgId);
        if (mapped) quotedWaMsgId = mapped.waMsgId;
      }

      for (const mapping of mappings) {
        const isGroupChat = msg.chat.type === 'group' || msg.chat.type === 'supergroup';
        const rawHeader = formatHeader(
          isGroupChat ? msg.chat.title : null,
          senderName,
          mapping.include_group_name,
          isGroupChat ? mapping.include_sender_name : false
        );
        const cleanHeader = rawHeader.replace(/<\/?b>/g, '');
        const outboundWaText = `${cleanHeader}${tgText}`;

        let session = getSession('default');
        if (!session || !session.sock || !session.isConnected) {
          for (const s of sessions.values()) {
            if (s.sock && s.isConnected) {
              session = s;
              break;
            }
          }
        }
        if (session && session.sock && session.isConnected) {
          try {
            const sendOptions = {};
            if (quotedWaMsgId) {
              sendOptions.quoted = { key: { remoteJid: mapping.wa_jid, id: quotedWaMsgId } };
            }
            const sentWaMsg = await session.sock.sendMessage(
              mapping.wa_jid,
              { text: outboundWaText },
              sendOptions
            );
            if (sentWaMsg && sentWaMsg.key && sentWaMsg.key.id) {
              recordMessageMap(
                sentWaMsg.key.id,
                tgChatId,
                msg.message_id,
                mapping.wa_jid,
                true,
                senderName
              );
            }
          } catch (waErr) {
            logger.error(
              { error: waErr.message, waJid: mapping.wa_jid },
              '❌ Error syncing Telegram message to WhatsApp'
            );
          }
        }
      }
    }
  } catch (err) {
    logger.warn({ error: err.message }, '⚠️ Error polling Telegram updates');
  }
}

export function startTelegramPolling(intervalMs = 3000) {
  if (pollingTimer) clearInterval(pollingTimer);
  pollingTimer = setInterval(processTelegramUpdates, intervalMs);
}

export function stopTelegramPolling() {
  if (pollingTimer) {
    clearInterval(pollingTimer);
    pollingTimer = null;
  }
}
