#!/usr/bin/with-contenv bashio
# shellcheck shell=bash

# ============================================================================
# Addon Startup Banner - Auto-generated by CI
# ============================================================================
_show_startup_banner() {
	local VERSION="${ADDON_VERSION:-2.0.0}"
	local SLUG="pterodactyl_wings"
	local UNSUPPORTED="false"
	local REPO="FaserF/hassio-addons"
	local MAINTAINER="FaserF"

	# Extract base version and commit from dev versions (1.2.3-dev+abc123)
	local BASE_VERSION="${VERSION%%-dev*}"
	local DEV_COMMIT=""
	if [[ "$VERSION" == *"+"* ]]; then
		DEV_COMMIT="${VERSION##*+}"
	fi

	# Status indicator
	if [ "$UNSUPPORTED" = "true" ]; then
		bashio::log.error "🚨 STATUS: UNSUPPORTED"
		bashio::log.error "   This addon is no longer maintained!"
	elif [[ "$VERSION" == *"-dev"* ]]; then
		bashio::log.warning "🚧 STATUS: DEVELOPMENT"
		bashio::log.warning "   This is a development build!"
	elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
		bashio::log.notice "🔬 STATUS: BETA"
		bashio::log.notice "   This addon is in beta testing."
	else
		bashio::log.green "✅ STATUS: STABLE"
	fi

	# Helper for semantic version comparison
	version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }

	# ========================================================================
	# Smart Update Check
	# ========================================================================
	if command -v curl &>/dev/null; then
		local UPDATE_MSG=""

		# Get latest stable version from config.yaml
		local LATEST_STABLE
		LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//' || true)

		if [ -n "$LATEST_STABLE" ]; then
			# For DEV versions: Check if there are newer commits for this addon
			if [[ "$VERSION" == *"-dev"* ]]; then
				if [ -n "$DEV_COMMIT" ]; then
					# Get latest commit for this addon from GitHub
					local LATEST_COMMIT
					LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7 || true)

					if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
						UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
						bashio::log.yellow "   Your commit: $DEV_COMMIT"
						bashio::log.yellow "   Latest: $LATEST_COMMIT"
					fi
				fi

				# Also check if a stable release is available
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# Compare versions
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
						bashio::log.yellow "   Consider upgrading to the stable release"
					fi
				fi

			# For BETA versions (< 1.0.0): Check for newer beta OR stable
			elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# If stable is >= 1.0.0, it's definitely newer
					local LATEST_MAJOR="${LATEST_STABLE%%.*}"
					if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
					elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi

			# For STABLE versions: Simple version comparison
			else
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi
			fi
		fi

		if [ -n "$UPDATE_MSG" ]; then
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
			bashio::log.yellow "$UPDATE_MSG"
			bashio::log.yellow "   You are running: $VERSION"
			bashio::log.yellow "   Update via the Add-on Store"
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
		fi
	fi

	# Footer with links
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info "📝 Issues: https://github.com/$REPO/issues"
	bashio::log.info "💖 Maintained by: $MAINTAINER"
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue &>/dev/null 2>&1; then
	_show_startup_banner
fi

# Enable strict mode
set -e
# shellcheck disable=SC1091

# Get Addon Version

config_file=$(bashio::config 'config_file')
#Create Shortcut to config file
echo "Using config file from ${config_file}..."

if [ ! -f "$config_file" ]; then
	bashio::log.warning "⚠️  Wings configuration file not found at ${config_file}!"
	bashio::log.info ""
	bashio::log.info "💡 Wings needs to be configured from the Pterodactyl Panel first:"
	bashio::log.info "   1. Install & configure the Pterodactyl Panel add-on"
	bashio::log.info "   2. Create a new Node in the Panel's admin section"
	bashio::log.info "   3. Download the config.yml from the Node configuration"
	bashio::log.info ""
	bashio::log.info "📦 Panel Add-on: https://github.com/FaserF/hassio-addons/tree/master/pterodactyl-panel"
	bashio::log.info ""
	bashio::log.warning "Creating default config for you at ${config_file}..."
	bashio::log.warning "Please edit this file with your node configuration details!"
	mkdir -p "$(dirname "$config_file")"
	if [ -f /etc/pterodactyl/config.yaml.default ]; then
		cp /etc/pterodactyl/config.yaml.default "$config_file"
	else
		bashio::log.error "Default config template not found!"
		touch "$config_file"
	fi
fi

mkdir -p /etc/pterodactyl
ln -sf "$config_file" /etc/pterodactyl/config.yml

echo "Starting Pterodactyl Daemon..."

# Check if using dummy config
if grep -q 'token: "example"' "$config_file"; then
	bashio::log.warning "-----------------------------------------------------------"
	bashio::log.warning " Add-on is NOT configured!"
	bashio::log.warning " You are using the default configuration template."
	bashio::log.warning " Please edit $config_file with your Panel's node configuration."
	bashio::log.warning " The add-on will wait here until you restart it with a valid config."
	bashio::log.warning "-----------------------------------------------------------"
	sleep infinity
fi

exec /usr/local/bin/wings
