build_from:
  armhf: "ghcr.io/hassio-addons/base:18.0.2"
  armv7: "ghcr.io/hassio-addons/base:18.0.2"
  aarch64: "ghcr.io/hassio-addons/base:18.0.2"
  amd64: "ghcr.io/hassio-addons/base:18.0.2"
  i386: "ghcr.io/hassio-addons/base:18.0.2"
