#!/usr/bin/env bashio

# <ADDON_BANNER_INJECTION>

# ============================================================================
# Addon Startup Banner - Auto-generated by CI
# ============================================================================
_show_startup_banner() {
    local VERSION="2.1.1"
    local NAME="Switch LAN Play Client"
    local SLUG="switch-lan-play"
    local UNSUPPORTED="false"
    local MAINTAINER="FaserF"
    local REPO="$MAINTAINER/hassio-addons"

    # Extract base version and commit from dev versions (1.2.3-dev+abc123)
    local BASE_VERSION="${VERSION%%-dev*}"
    local DEV_COMMIT=""
    if [[ "$VERSION" == *"+""*" ]]; then
        DEV_COMMIT="${VERSION##*+}"
    fi

    # Header
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.blue "  🏠 $NAME"
    bashio::log.blue "  📦 Version: $VERSION"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Status indicator
    if [ "$UNSUPPORTED" = "true" ]; then
        bashio::log.error "🚨 STATUS: UNSUPPORTED"
        bashio::log.error "   This addon is no longer maintained!"
    elif [[ "$VERSION" == *"-dev"* ]]; then
        bashio::log.warning "🚧 STATUS: DEVELOPMENT"
        bashio::log.warning "   This is a development build!"
    elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
        bashio::log.notice "🔬 STATUS: BETA"
        bashio::log.notice "   This addon is in beta testing."
    else
        bashio::log.green "✅ STATUS: STABLE"
    fi

    # Helper for semantic version comparison (Pure Bash)
    # Returns 0 if $1 > $2, 1 otherwise
    version_gt() {
        local v1="$1"
        local v2="$2"
        if [ "$v1" = "$v2" ]; then return 1; fi

        local IFS=.
        local i ver1 ver2
        read -ra ver1 <<< "$v1"
        read -ra ver2 <<< "$v2"

        # Pad with zeros
        for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do ver1[i]=0; done
        for ((i=${#ver2[@]}; i<${#ver1[@]}; i++)); do ver2[i]=0; done

        for ((i=0; i<${#ver1[@]}; i++)); do
            # Handle non-numeric (e.g. dev versions) by treating as 0
            local n1="${ver1[i] preg_replace '[^0-9]' ''}"
            local n2="${ver2[i] preg_replace '[^0-9]' ''}"
            # Fallback for pure bash without regex substitution if needed, but lets assume simple numbers for stable check
            # Simple sanitization: remove anything not a digit
            n1=$(echo "${ver1[i]}" | tr -cd '0-9')
            n2=$(echo "${ver2[i]}" | tr -cd '0-9')

            # Empty string -> 0
            [ -z "$n1" ] && n1=0
            [ -z "$n2" ] && n2=0

            if ((10#$n1 > 10#$n2)); then return 0; fi
            if ((10#$n1 < 10#$n2)); then return 1; fi
        done
        return 1
    }

    # ========================================================================
    # Smart Update Check
    # ========================================================================
    if command -v curl &>/dev/null; then
        local UPDATE_MSG=""

        # Ensure we don't fail on pipe errors
        local LATEST_STABLE=""

        # Get latest stable version from config.yaml
        if LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//'); then
            : # Success
        else
            LATEST_STABLE=""
        fi

        if [ -n "$LATEST_STABLE" ]; then
            # For DEV versions: Check if there are newer commits for this addon
            if [[ "$VERSION" == *"-dev"* ]]; then
                if [ -n "$DEV_COMMIT" ]; then
                    # Get latest commit for this addon from GitHub
                    local LATEST_COMMIT=""
                    if LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7); then
                         :
                    fi

                    if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
                        UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
                        bashio::log.yellow "   Your commit: $DEV_COMMIT"
                        bashio::log.yellow "   Latest: $LATEST_COMMIT"
                    fi
                fi

                # Also check if a stable release is available
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # Compare versions
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                        bashio::log.yellow "   Consider upgrading to the stable release"
                    fi
                fi

            # For BETA versions (< 1.0.0): Check for newer beta OR stable
            elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # If stable is >= 1.0.0, it's definitely newer
                    local LATEST_MAJOR="${LATEST_STABLE%%.*}"
                    if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                    elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi

            # For STABLE versions: Simple version comparison
            else
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi
            fi
        fi

        if [ -n "$UPDATE_MSG" ]; then
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            bashio::log.yellow "$UPDATE_MSG"
            bashio::log.yellow "   You are running: $VERSION"
            bashio::log.yellow "   Update via the Add-on Store"
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        fi
    fi

    # Footer with links
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info "📝 Issues: https://github.com/$REPO/issues"
    bashio::log.info "💖 Maintained by: $MAINTAINER"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue &>/dev/null 2>&1; then
    _show_startup_banner
fi

# </ADDON_BANNER_INJECTION>





# Enable strict mode
set -e
# shellcheck disable=SC1091

#VARIABLES
#VARIABLES
bashio::log.info "Loading configuration..."

if bashio::config.exists 'server'; then
	server=$(bashio::config 'server')
	bashio::log.info "Using server: $server"
else
	bashio::log.error "Configuration 'server' is missing!"
	bashio::exit.nok
fi

if bashio::config.exists 'log_level'; then
	log_level=$(bashio::config 'log_level')
else
	log_level="info"
fi
bashio::log.info "Log level: $log_level"

# Helpful hint for self-hosting
bashio::log.info "💡 Tip: Want to host your own server instead of using public ones?"
bashio::log.info "   Check out the Switch LAN Play Server add-on:"
bashio::log.info "   https://github.com/FaserF/hassio-addons/tree/master/switch_lan_play_server"
bashio::log.info ""

echo "For more informations or bugs with lan-play itself please visit: https://github.com/spacemeowx2/switch-lan-play"
echo "If you want to install the latest lan-play client, please reinstall this addon"
echo "Starting lan-play Client with the server: $server - To Connect your switch with this client have a look at https://github.com/spacemeowx2/switch-lan-play#2-switch"

# Build command arguments
LAN_PLAY_ARGS=("--relay-server-addr" "$server")

# Ensure stdout and stderr are unbuffered
export PYTHONUNBUFFERED=1

# Use exec to replace shell process with lan-play
# If log level is not debug, filter out [DEBUG]: lines
if [ "$log_level" = "debug" ]; then
	bashio::log.info "Debug logging enabled - all debug messages will be shown"
	# Show all output including debug
	exec /usr/local/bin/lan-play "${LAN_PLAY_ARGS[@]}" 2>&1
else
	bashio::log.info "Info logging enabled - debug messages will be filtered"
	# Filter out [DEBUG]: lines
	# Note: grep becomes the main process, but healthcheck still works as it checks for lan-play process
	exec /usr/local/bin/lan-play "${LAN_PLAY_ARGS[@]}" 2>&1 | grep -v "^\[DEBUG\]:"
fi
