#!/usr/bin/with-contenv bashio
# shellcheck disable=SC2034,SC2129,SC2016
# shellcheck shell=bash

# <ADDON_BANNER_INJECTION>

# ============================================================================
# Addon Startup Banner - Auto-generated by CI
# ============================================================================
_show_startup_banner() {
	local VERSION
	if ! VERSION=$(bashio::addon.version 2>/dev/null); then
		VERSION="unknown"
	fi
	if [ -z "$VERSION" ]; then
		VERSION="unknown"
	fi
	local NAME="Wiki.JS"
	local SLUG="wiki.js"
	local UNSUPPORTED="false"
	local MAINTAINER="FaserF"
	local REPO="$MAINTAINER/hassio-addons"

	# Extract base version and commit from dev versions (1.2.3-dev+abc123)
	local BASE_VERSION="${VERSION%%-dev*}"
	local DEV_COMMIT=""
	if [[ "$VERSION" == *"+"* ]]; then
		DEV_COMMIT="${VERSION##*+}"
	fi

	# Status indicator
	if [ "$UNSUPPORTED" = "true" ]; then
		bashio::log.error "🚨 STATUS: UNSUPPORTED"
		bashio::log.error "   This addon is no longer maintained!"
	elif [[ "$VERSION" == *"-dev"* ]]; then
		bashio::log.warning "🚧 STATUS: DEVELOPMENT"
		bashio::log.warning "   This is a development build!"
	elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
		bashio::log.notice "🔬 STATUS: BETA"
		bashio::log.notice "   This addon is in beta testing."
	else
		bashio::log.green "✅ STATUS: STABLE"
	fi

	# Helper for semantic version comparison (Pure Bash)
	# Returns 0 if $1 > $2, 1 otherwise
	version_gt() {
		local v1="$1"
		local v2="$2"
		if [ "$v1" = "$v2" ]; then return 1; fi

		local IFS=.
		local i ver1 ver2
		read -ra ver1 <<<"$v1"
		read -ra ver2 <<<"$v2"

		# Pad with zeros
		for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do ver1[i]=0; done
		for ((i = ${#ver2[@]}; i < ${#ver1[@]}; i++)); do ver2[i]=0; done

		for ((i = 0; i < ${#ver1[@]}; i++)); do
			# Handle non-numeric (e.g. dev versions) by treating as 0
			# Simple sanitization: remove anything not a digit using bash expansion
			local n1="${ver1[i]//[!0-9]/}"
			local n2="${ver2[i]//[!0-9]/}"

			# Fallback (rarely needed if using bash, but harmless to keep if desired,
			# though user suggestion implies we can rely on bash expansion)
			# We will use the bash expansion result directly.

			# Empty string -> 0
			[ -z "$n1" ] && n1=0
			[ -z "$n2" ] && n2=0

			if ((10#$n1 > 10#$n2)); then return 0; fi
			if ((10#$n1 < 10#$n2)); then return 1; fi
		done
		return 1
	}

	# ========================================================================
	# Smart Update Check
	# ========================================================================
	if command -v curl &>/dev/null; then
		local UPDATE_MSG=""

		# Ensure we don't fail on pipe errors
		local LATEST_STABLE=""

		# Get latest stable version from config.yaml
		if LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//'); then
			: # Success
		else
			LATEST_STABLE=""
		fi

		if [ -n "$LATEST_STABLE" ]; then
			# For DEV versions: Check if there are newer commits for this addon
			if [[ "$VERSION" == *"-dev"* ]]; then
				if [ -n "$DEV_COMMIT" ]; then
					# Get latest commit for this addon from GitHub
					local LATEST_COMMIT=""
					if LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7); then
						:
					fi

					if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
						UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
						bashio::log.yellow "   Your commit: $DEV_COMMIT"
						bashio::log.yellow "   Latest: $LATEST_COMMIT"
					fi
				fi

				# Also check if a stable release is available
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# Compare versions
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
						bashio::log.yellow "   Consider upgrading to the stable release"
					fi
				fi

			# For BETA versions (< 1.0.0): Check for newer beta OR stable
			elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# If stable is >= 1.0.0, it's definitely newer
					local LATEST_MAJOR="${LATEST_STABLE%%.*}"
					if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
					elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi

			# For STABLE versions: Simple version comparison
			else
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi
			fi
		fi

		if [ -n "$UPDATE_MSG" ]; then
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
			bashio::log.yellow "$UPDATE_MSG"
			bashio::log.yellow "   You are running: $VERSION"
			bashio::log.yellow "   Update via the Add-on Store"
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
		fi
	fi

	# Footer with links
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info "📝 Issues: https://github.com/$REPO/issues"
	bashio::log.info "💖 Maintained by: $MAINTAINER"
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue &>/dev/null 2>&1; then
	_show_startup_banner
fi

# </ADDON_BANNER_INJECTION>

# Enable strict mode
set -e
# shellcheck disable=SC1091

ssl=$(bashio::config 'ssl')
certfile=$(bashio::config 'certfile')
keyfile=$(bashio::config 'keyfile')

if ! log_level=$(bashio::config 'log_level') || [ -z "$log_level" ]; then
	bashio::log.warning "Failed to fetch log_level configuration. Using default: info"
	log_level="info"
fi

# Map Bashio log_level to Wiki.js log_level
# Bashio: trace, debug, info, notice, warning, error, fatal
# Wiki.js: error, warn, info, verbose, debug, silly
# We map loosely:
wiki_log_level="info"
case "${log_level}" in
trace) wiki_log_level="silly" ;;
debug) wiki_log_level="debug" ;;
info) wiki_log_level="info" ;;
notice) wiki_log_level="info" ;;
warning) wiki_log_level="warn" ;;
error) wiki_log_level="error" ;;
fatal) wiki_log_level="error" ;;
*) wiki_log_level="info" ;;
esac

declare host
declare password
declare port
declare username

if [ "$ssl" = "true" ]; then
	echo "You have activated SSL. SSL Settings will be applied"
	if [ ! -f "/ssl/$certfile" ]; then
		bashio::log.error "Cannot find certificate file $certfile . Turn off SSL or check for if the file really exists at /ssl/"
		exit 1
	fi
	if [ ! -f "/ssl/$keyfile" ]; then
		bashio::log.error "Cannot find certificate key file $keyfile . Turn off SSL or check for if the file really exists at /ssl/"
		exit 1
	fi
fi

# Require mariadb service to be available
if ! bashio::services.available "mysql"; then
	bashio::log.error "This add-on requires the MariaDB core add-on 2.0 or newer!"
	bashio::exit.nok "Make sure the MariaDB add-on is installed and running"
fi

host=$(bashio::services "mysql" "host")
password=$(bashio::services "mysql" "password")
port=$(bashio::services "mysql" "port")
username=$(bashio::services "mysql" "username")

if [ -z "$host" ]; then
	bashio::log.warning "MariaDB connection details not found. Waiting..."
	# Retry for up to 5 minutes (30 * 10s)
	for i in {1..30}; do
		sleep 10
		host=$(bashio::services "mysql" "host")
		if [ -n "$host" ]; then
			break
		fi
		bashio::log.debug "Waiting for MariaDB... ($i/30)"
	done

	if [ -z "$host" ]; then
		bashio::log.error "MariaDB not found after waiting. Exiting."
		exit 1
	fi
	# Refresh other variables if host found later
	password=$(bashio::services "mysql" "password")
	port=$(bashio::services "mysql" "port")
	username=$(bashio::services "mysql" "username")
fi

# Git Support Setup - Define variables early for potential cleanup
GIT_DATA_DIR="/addon_configs/wiki.js/git"
GIT_SSH_DIR="$GIT_DATA_DIR/ssh"
GIT_REPO_DIR="$GIT_DATA_DIR/repo"

# Create directories for Git storage
mkdir -p "$GIT_SSH_DIR" "$GIT_REPO_DIR"
chmod 700 "$GIT_SSH_DIR"

#Drop database based on config flag (with safeguards)
if bashio::config.true 'reset_database'; then
	if ! bashio::config.true 'reset_database_confirm'; then
		bashio::log.error "Database reset requires both 'reset_database' and 'reset_database_confirm' to be enabled!"
		bashio::log.error "This is a DESTRUCTIVE operation that will DELETE ALL DATA!"
		bashio::log.error "Set 'reset_database_confirm: true' in your configuration to proceed."
		exit 1
	fi

	bashio::log.warning "=========================================="
	bashio::log.warning "WARNING: DESTRUCTIVE DATABASE OPERATION"
	bashio::log.warning "=========================================="
	bashio::log.warning "This will DROP the entire 'wiki' database!"
	bashio::log.warning "All data will be permanently lost!"
	bashio::log.warning "=========================================="

	# Create timestamped backup before dropping
	BACKUP_DIR="/config/backups"
	mkdir -p "$BACKUP_DIR"
	TIMESTAMP=$(date +%Y%m%d_%H%M%S)
	BACKUP_FILE="$BACKUP_DIR/wiki_backup_${TIMESTAMP}.sql"

	bashio::log.info "Creating backup before database reset..."
	bashio::log.info "Backup location: $BACKUP_FILE"

	# Create backup using mysqldump with MYSQL_PWD for security
	export MYSQL_PWD="${password}"
	if mysqldump -h "${host}" -P "${port}" -u "${username}" --skip-ssl wiki >"$BACKUP_FILE" 2>/dev/null; then
		bashio::log.info "Backup created successfully: $BACKUP_FILE"
	else
		bashio::log.warning "Backup failed (database may not exist yet), continuing with reset..."
	fi
	unset MYSQL_PWD

	bashio::log.warning 'Recreating database (dropping existing if present)...'
	echo "DROP DATABASE IF EXISTS wiki;" |
		MYSQL_PWD="${password}" mariadb -h "${host}" -P "${port}" -u "${username}" --skip_ssl

	#Remove reset_database options
	bashio::addon.option 'reset_database'
	bashio::addon.option 'reset_database_confirm'

	bashio::log.warning "Cleaning up Git storage and SSH keys..."
	# shellcheck disable=SC2115
	rm -rf "$GIT_DATA_DIR/ssh/"*
	# shellcheck disable=SC2115
	rm -rf "$GIT_DATA_DIR/repo/"*
fi

# Configure SSH to use custom key location
# Support multiple key types: RSA, ECDSA, Ed25519
for key_type in id_rsa id_ecdsa id_ed25519; do
	if [ -f "$GIT_SSH_DIR/$key_type" ]; then
		bashio::log.info "Git SSH key found: $key_type"
		export GIT_SSH_COMMAND="ssh -i $GIT_SSH_DIR/$key_type -o StrictHostKeyChecking=no"
		break
	fi
done

# Populate known_hosts to avoid first-connect errors
if [ ! -f "$GIT_SSH_DIR/known_hosts" ]; then
	bashio::log.info "Populating known_hosts for common git providers..."
	touch "$GIT_SSH_DIR/known_hosts"
	ssh-keyscan github.com gitlab.com bitbucket.org >>"$GIT_SSH_DIR/known_hosts" 2>/dev/null || true
	chmod 644 "$GIT_SSH_DIR/known_hosts"
fi

bashio::log.info "Git support enabled. SSH keys can be placed in $GIT_SSH_DIR"
bashio::log.info "Local repository path for Wiki.js: $GIT_REPO_DIR"
# Ensure /config directory exists
mkdir -p /config

# Generate configuration content once
CONFIG_CONTENT=$(
	cat <<EOF
port: 3010
db:
  type: mariadb
  host: ${host}
  port: ${port}
  user: ${username}
  pass: ${password}
  db: wiki
ssl:
  enabled: ${ssl}
  port: 3443
  provider: custom
  format: pem
  key: /ssl/${keyfile}
  cert: /ssl/${certfile}
pool:
bindIP: 0.0.0.0

logLevel: ${wiki_log_level}
offline: false

ha: false
dataPath: ./data
EOF
)

# Create Config file at the location Wiki.js expects
CONFIG_FILE="/config/wikijs-config.yml"
if [ ! -f "$CONFIG_FILE" ]; then
	bashio::log.info "Configuration file not found. Creating $CONFIG_FILE..."
	echo "$CONFIG_CONTENT" >"$CONFIG_FILE"
	bashio::log.info "Configuration file created successfully."
else
	bashio::log.info "Configuration file already exists at $CONFIG_FILE. Updating with current settings..."
	echo "$CONFIG_CONTENT" >"$CONFIG_FILE"
	bashio::log.info "Configuration file updated successfully."
fi

# Also create config.yml in /wiki for backward compatibility
echo "$CONFIG_CONTENT" >/wiki/config.yml

# Create database if not exists
echo "CREATE DATABASE IF NOT EXISTS wiki;" |
	MYSQL_PWD="${password}" mariadb -h "${host}" -P "${port}" -u "${username}" --skip_ssl

# Verify config file exists before starting
if [ ! -f "$CONFIG_FILE" ]; then
	bashio::log.error "Configuration file $CONFIG_FILE was not created! Cannot start Wiki.js."
	exit 1
fi

bashio::log.info "Configuration file verified at $CONFIG_FILE"
bashio::log.info "Starting Wiki.JS from /wiki directory..."

# Set environment variable to tell Wiki.js where to find the config file
export CONFIG_FILE="$CONFIG_FILE"

# Change to wiki directory and start
cd /wiki || exit 1
exec node server
