#!/usr/bin/with-contenv bashio
# shellcheck shell=bash

# <ADDON_BANNER_INJECTION>

# ============================================================================
# Addon Startup Banner - Auto-generated by CI
# ============================================================================
_show_startup_banner() {
    local VERSION="2.0.0"
    local NAME="Solumati"
    local SLUG="solumati"
    local UNSUPPORTED="false"
    local REPO="FaserF/hassio-addons"
    local MAINTAINER="FaserF"

    # Extract base version and commit from dev versions (1.2.3-dev+abc123)
    local BASE_VERSION="${VERSION%%-dev*}"
    local DEV_COMMIT=""
    if [[ "$VERSION" == *"+""*" ]]; then
        DEV_COMMIT="${VERSION##*+}"
    fi

    # Header
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.blue "  🏠 $NAME"
    bashio::log.blue "  📦 Version: $VERSION"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Status indicator
    if [ "$UNSUPPORTED" = "true" ]; then
        bashio::log.error "🚨 STATUS: UNSUPPORTED"
        bashio::log.error "   This addon is no longer maintained!"
    elif [[ "$VERSION" == *"-dev"* ]]; then
        bashio::log.warning "🚧 STATUS: DEVELOPMENT"
        bashio::log.warning "   This is a development build!"
    elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
        bashio::log.notice "🔬 STATUS: BETA"
        bashio::log.notice "   This addon is in beta testing."
    else
        bashio::log.green "✅ STATUS: STABLE"
    fi

    # Helper for semantic version comparison
    version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }

    # ========================================================================
    # Smart Update Check
    # ========================================================================
    if command -v curl &>/dev/null; then
        local UPDATE_MSG=""

        # Get latest stable version from config.yaml
        local LATEST_STABLE
        LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//')

        if [ -n "$LATEST_STABLE" ]; then
            # For DEV versions: Check if there are newer commits for this addon
            if [[ "$VERSION" == *"-dev"* ]]; then
                if [ -n "$DEV_COMMIT" ]; then
                    # Get latest commit for this addon from GitHub
                    local LATEST_COMMIT
                    LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7)

                    if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
                        UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
                        bashio::log.yellow "   Your commit: $DEV_COMMIT"
                        bashio::log.yellow "   Latest: $LATEST_COMMIT"
                    fi
                fi

                # Also check if a stable release is available
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # Compare versions
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                        bashio::log.yellow "   Consider upgrading to the stable release"
                    fi
                fi

            # For BETA versions (< 1.0.0): Check for newer beta OR stable
            elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # If stable is >= 1.0.0, it's definitely newer
                    local LATEST_MAJOR="${LATEST_STABLE%%.*}"
                    if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                    elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi

            # For STABLE versions: Simple version comparison
            else
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi
            fi
        fi

        if [ -n "$UPDATE_MSG" ]; then
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            bashio::log.yellow "$UPDATE_MSG"
            bashio::log.yellow "   You are running: $VERSION"
            bashio::log.yellow "   Update via the Add-on Store"
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        fi
    fi

    # Footer with links
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info "📝 Issues: https://github.com/$REPO/issues"
    bashio::log.info "💖 Maintained by: $MAINTAINER"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue &>/dev/null 2>&1; then
    _show_startup_banner
fi

# </ADDON_BANNER_INJECTION>



# Enable strict mode
set -e
# shellcheck disable=SC1091

# Get Addon Version

# --- CONFIGURATION ---
DATA_DIR="/data/postgresql"
IMAGES_DIR="/data/images"
DB_USER="solumati"
DB_NAME="solumatidb"

bashio::log.info "Starting Solumati Add-on initialization..."

# --- FACTORY RESET CHECK (DANGEROUS!) ---
if bashio::config.true 'factory_reset'; then
	bashio::log.warning "=================================================="
	bashio::log.warning "   ⚠️  FACTORY RESET ENABLED  ⚠️"
	bashio::log.warning "=================================================="
	bashio::log.warning "ALL DATA WILL BE PERMANENTLY DELETED!"
	bashio::log.warning "This includes:"
	bashio::log.warning "  - All user accounts"
	bashio::log.warning "  - All messages and conversations"
	bashio::log.warning "  - All uploaded images"
	bashio::log.warning "  - All settings and configurations"
	bashio::log.warning "=================================================="

	# Wait 5 seconds to give user time to cancel
	bashio::log.warning "Starting reset in 5 seconds... (Stop add-on NOW to abort)"
	sleep 5

	bashio::log.info "Proceeding with factory reset..."

	# Stop PostgreSQL if running
	if [ -d "$DATA_DIR" ]; then
		bashio::log.info "Stopping PostgreSQL..."
		su postgres -c "pg_ctl stop -D $DATA_DIR -m immediate" 2>/dev/null || true
	fi

	# Delete all data
	bashio::log.info "Deleting database..."
	rm -rf "$DATA_DIR"

	bashio::log.info "Deleting uploaded images..."
	rm -rf "$IMAGES_DIR"

	bashio::log.info "=================================================="
	bashio::log.info "   ✅ FACTORY RESET COMPLETE"
	bashio::log.info "=================================================="
	bashio::log.info "All data has been deleted."
	bashio::log.info "The add-on will now restart with a fresh database."
	bashio::log.info ""
	bashio::log.warning "IMPORTANT: Disable 'factory_reset' in the add-on settings!"
	bashio::log.warning "Otherwise, the database will be wiped again on next restart."
	bashio::log.info "=================================================="

	# Continue with normal startup (fresh database will be created)
fi

# --- READ CONFIGURATION FROM HA UI ---
bashio::log.info "Reading configuration from Home Assistant..."

# Log Level (convert to uppercase for Python logging)
if bashio::config.has_value 'log_level'; then
	LOG_LEVEL=$(bashio::config 'log_level' | tr '[:lower:]' '[:upper:]')
	# Map HA log levels to Python log levels
	case "$LOG_LEVEL" in
	TRACE | DEBUG) LOG_LEVEL="DEBUG" ;;
	NOTICE | INFO) LOG_LEVEL="INFO" ;;
	WARNING) LOG_LEVEL="WARNING" ;;
	ERROR | FATAL) LOG_LEVEL="ERROR" ;;
	*) LOG_LEVEL="INFO" ;;
	esac
	export LOG_LEVEL
	bashio::log.info "Log level set to: $LOG_LEVEL"
fi

# Test Mode
if bashio::config.true 'test_mode'; then
	export TEST_MODE="true"
	bashio::log.info "Test mode: ENABLED (dummy data will be generated)"
else
	export TEST_MODE="false"
fi

# Marketing Page
if bashio::config.true 'marketing_page_enabled'; then
	export ENABLE_MARKETING_PAGE="true"
	bashio::log.info "Marketing Page: ENABLED"
else
	export ENABLE_MARKETING_PAGE="false"
	bashio::log.info "Marketing Page: DISABLED"
fi

# App Base URL (for emails, links, etc.)
if bashio::config.has_value 'app_base_url' && [ -n "$(bashio::config 'app_base_url')" ]; then
	APP_BASE_URL=$(bashio::config 'app_base_url')
	export APP_BASE_URL
	bashio::log.info "App base URL set to: $APP_BASE_URL"
else
	# Try to auto-detect from Ingress
	if bashio::var.has_value "$(bashio::addon.ingress_url)"; then
		APP_BASE_URL="$(bashio::addon.ingress_url)"
		export APP_BASE_URL
		bashio::log.info "App base URL auto-detected from Ingress: $APP_BASE_URL"
	else
		export APP_BASE_URL="http://homeassistant.local:8099"
		bashio::log.info "App base URL set to default: $APP_BASE_URL"
	fi
fi

# --- DEV MODE: USE MAIN BRANCH ---
if bashio::config.true 'dev_use_main_branch'; then
	bashio::log.warning "=================================================="
	bashio::log.warning "   ⚠️  DEVELOPER MODE ENABLED  ⚠️"
	bashio::log.warning "=================================================="
	bashio::log.warning "Using latest code from 'main' branch."
	bashio::log.warning "Downloading and rebuilding... This will take time!"
	bashio::log.warning "Please wait..."

	# Download main branch
	cd /tmp || exit 1

	download_branch() {
		local BRANCH=$1
		local URL="https://github.com/FaserF/Solumati/archive/refs/heads/$BRANCH.tar.gz"
		local HEADER_ARGS=""

		# Check for GitHub Token
		if bashio::config.has_value 'github_token' && [ -n "$(bashio::config 'github_token')" ]; then
			bashio::log.info "Using GitHub Token for authentication..."
			HEADER_ARGS="-H \"Authorization: token $(bashio::config 'github_token')\""
		fi

		bashio::log.info "Attempting to download branch: $BRANCH"

		# Use eval to properly handle quoted arguments in HEADER_ARGS
		# -f: Fail silently (no output at all) on server errors
		# -L: Follow redirects
		# -s: Silent mode
		# -S: Show error message if it fails
		# shellcheck disable=SC2086
		if eval curl -fL -s -S $HEADER_ARGS "$URL" -o main.tar.gz; then
			return 0
		else
			return 1
		fi
	}

	if download_branch "main" || download_branch "master"; then
		bashio::log.info "Download successful. Extracting..."
		rm -rf /tmp/solumati-main
		mkdir -p /tmp/solumati-main

		if tar -xzf main.tar.gz -C /tmp/solumati-main --strip-components=1; then
			bashio::log.info "Extraction successful."
		else
			bashio::log.error "Extraction failed! The downloaded file might be invalid."
			bashio::log.error "File size: $(du -h main.tar.gz | cut -f1)"
			bashio::log.error "First 100 bytes of content:"
			head -c 100 main.tar.gz
			rm main.tar.gz
			exit 1
		fi

		# Update Backend
		bashio::log.info "Updating Backend code..."
		if [ -d "/tmp/solumati-main/backend" ]; then
			cp -r /tmp/solumati-main/backend/* /app/backend/

			# Install potentially new python requirements
			if [ -f "/app/backend/requirements.txt" ]; then
				bashio::log.info "Installing Python dependencies..."
				pip install --no-cache-dir -r /app/backend/requirements.txt
			fi
		else
			bashio::log.error "Backend directory not found in downloaded archive!"
		fi

		# Rebuild Frontend
		bashio::log.info "Rebuilding Frontend (this may take several minutes)..."
		if [ -d "/tmp/solumati-main/frontend" ]; then
			# Create temp build dir
			rm -rf /tmp/frontend_build
			mkdir -p /tmp/frontend_build
			cp -r /tmp/solumati-main/frontend/* /tmp/frontend_build/

			cd /tmp/frontend_build || exit 1

			# IMPORTANT: Apply config.js fix found in Dockerfile
			if [ -f "src/config.js" ]; then
				if [ -f "vite.config.ts" ]; then
					sed -i "s|defineConfig({|defineConfig({ base: './',|g" vite.config.ts
				else
					sed -i "s|defineConfig({|defineConfig({ base: './',|g" vite.config.js
				fi
				sed -i "s|export const API_URL = .*|export const API_URL = './api';|g" src/config.js
				sed -i "s|const API_URL = .*|const API_URL = './api';|g" src/config.js
			fi

			bashio::log.info "Running 'npm install'..."
			if npm install; then
				bashio::log.info "Running 'npm run build'..."
				if npm run build; then
					bashio::log.info "Frontend build successful. Updating files..."
					# Remove old frontend files (preserve dir)
					rm -rf /app/frontend/*
					if [ -d "dist" ]; then
						cp -r dist/* /app/frontend/
					else
						bashio::log.error "'dist' directory not found after build!"
					fi
				else
					bashio::log.error "Frontend build failed! Keeping old frontend."
				fi
			else
				bashio::log.error "npm install failed! Keeping old frontend."
			fi
		else
			bashio::log.error "Frontend directory not found in downloaded archive!"
		fi

		# Cleanup
		rm -rf /tmp/main.tar.gz /tmp/solumati-main /tmp/frontend_build
		cd / || exit 1

		bashio::log.info "=================================================="
		bashio::log.info "   ✅ DEV MODE UPDATE COMPLETE"
		bashio::log.info "=================================================="
	else
		bashio::log.error "Failed to download main/master branch from GitHub!"
		bashio::log.error "If this is a private repository, please configure 'github_token' in the add-on options."
	fi
else
	bashio::log.info "Production Mode: Using packaged version."
fi

# Generate random password for database
DB_PASS=$(
	tr -dc A-Za-z0-9 </dev/urandom | head -c 32
	echo ''
)

# --- POSTGRESQL SETUP ---
if [ ! -d "$DATA_DIR" ]; then
	bashio::log.info "Initializing PostgreSQL data directory in $DATA_DIR..."
	mkdir -p "$DATA_DIR"
	chown postgres:postgres "$DATA_DIR"

	# Initialize DB
	su postgres -c "initdb -D $DATA_DIR"
fi

# Ensure Postgres directories permissions are correct (in case of restore/restart)
mkdir -p /run/postgresql
chown -R postgres:postgres /run/postgresql
chown -R postgres:postgres "$DATA_DIR"

# Start Postgres in background
bashio::log.info "Starting PostgreSQL service..."
if ! su postgres -c "pg_ctl start -D $DATA_DIR -l /var/lib/postgresql/log.log"; then
	bashio::log.error "Failed to start PostgreSQL service"
	exit 1
fi

# Wait for DB to be ready
bashio::log.info "Waiting for database to be ready..."
until su postgres -c "pg_isready"; do
	sleep 1
done

# --- IDEMPOTENT DB CONFIGURATION ---
# Run this every time to ensure user exists even if first setup crashed
bashio::log.info "Ensuring database user and schema exist..."
su postgres -c "createuser -s $DB_USER" || true
su postgres -c "createdb -O $DB_USER $DB_NAME" || true
echo "ALTER USER $DB_USER WITH PASSWORD '$DB_PASS';" | su postgres -c "psql"

# --- PERSISTENCE SETUP ---
# Handle uploaded images persistence
if [ ! -d "$IMAGES_DIR" ]; then
	mkdir -p "$IMAGES_DIR"
fi

mkdir -p /app/backend/static

# Remove the container's static/images dir and symlink to persistent storage
rm -rf /app/backend/static/images
ln -s "$IMAGES_DIR" /app/backend/static/images

# --- BACKEND START ---
export DATABASE_URL="postgresql://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME"

bashio::log.info "Starting Backend (Uvicorn)..."
bashio::log.info "Environment: TEST_MODE=$TEST_MODE, LOG_LEVEL=${LOG_LEVEL:-INFO}"
cd /app/backend || exit 1
# Start Uvicorn in background
uvicorn app.main:app --host 127.0.0.1 --port 7777 &
BACKEND_PID=$!

# --- NGINX START ---
bashio::log.info "Starting Nginx (Frontend)..."
mkdir -p /run/nginx
nginx -g "daemon off;" &
NGINX_PID=$!

bashio::log.info "Solumati is now running!"
bashio::log.info "Access via Home Assistant Ingress or http://homeassistant.local:8099"

# Trap signals to stop processes correctly
cleanup() {
	bashio::log.info "Shutting down services..."

	# Stop Nginx gracefully
	kill -TERM $NGINX_PID 2>/dev/null
	wait $NGINX_PID 2>/dev/null

	# Stop Backend gracefully
	kill -TERM $BACKEND_PID 2>/dev/null
	wait $BACKEND_PID 2>/dev/null

	# Stop PostgreSQL gracefully (smart mode)
	su postgres -c "pg_ctl stop -D $DATA_DIR -m smart" || true

	bashio::log.info "All services stopped"
	exit 0
}

trap cleanup SIGTERM SIGHUP

wait $NGINX_PID
