build_from:
  armhf: "ghcr.io/hassio-addons/base-python:16.0.1"
  armv7: "ghcr.io/hassio-addons/base-python:16.0.1"
  aarch64: "ghcr.io/hassio-addons/base-python:16.0.1"
  amd64: "ghcr.io/hassio-addons/base-python:16.0.1"
  i386: "ghcr.io/hassio-addons/base-python:16.0.1"
