name: "DBF (DB-Infoscreen) (Edge)"
version: "1.1.3"
slug: "dbf"
description: "Railway departure display (formerly db-fakescreen) as a Home Assistant App."
url: "https://github.com/FaserF/ha-db_infoscreen"
arch:
  - aarch64
  - amd64
init: false
host_network: true
ingress: true
ingress_port: 8092
ingress_entry: "/"
panel_icon: "mdi:train"

discovery:
  - db_infoscreen
map:
  - homeassistant_config:rw
ports:
  8092/tcp: 8092
ports_description:
  8092/tcp: "Web Interface (Required for HA App integration, not needed for Ingress)"
options:
  log_level: info
  workers: 2
  imprint_name: ""
  imprint_address: ""
  privacy_policy_url: ""
  auto_install_integration: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  workers: int?
  imprint_name: str?
  imprint_address: str?
  privacy_policy_url: str?
  auto_install_integration: bool?
stage: experimental
