#!/bin/bash
# shellcheck disable=SC1091,SC2034,SC2129,SC2016

# <ADDON_BANNER_INJECTION>

# ============================================================================
# Addon Startup Banner - Auto-generated by CI
# ============================================================================
_show_startup_banner() {
    local VERSION="2.0.0"
    local NAME="ShieldFile"
    local SLUG="shieldfile"
    local UNSUPPORTED="false"
    local REPO="FaserF/hassio-addons"
    local MAINTAINER="FaserF"

    # Extract base version and commit from dev versions (1.2.3-dev+abc123)
    local BASE_VERSION="${VERSION%%-dev*}"
    local DEV_COMMIT=""
    if [[ "$VERSION" == *"+""*" ]]; then
        DEV_COMMIT="${VERSION##*+}"
    fi

    # Header
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.blue "  🏠 $NAME"
    bashio::log.blue "  📦 Version: $VERSION"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Status indicator
    if [ "$UNSUPPORTED" = "true" ]; then
        bashio::log.error "🚨 STATUS: UNSUPPORTED"
        bashio::log.error "   This addon is no longer maintained!"
    elif [[ "$VERSION" == *"-dev"* ]]; then
        bashio::log.warning "🚧 STATUS: DEVELOPMENT"
        bashio::log.warning "   This is a development build!"
    elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
        bashio::log.notice "🔬 STATUS: BETA"
        bashio::log.notice "   This addon is in beta testing."
    else
        bashio::log.green "✅ STATUS: STABLE"
    fi

    # Helper for semantic version comparison
    version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }

    # ========================================================================
    # Smart Update Check
    # ========================================================================
    if command -v curl &>/dev/null; then
        local UPDATE_MSG=""

        # Get latest stable version from config.yaml
        local LATEST_STABLE
        LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//')

        if [ -n "$LATEST_STABLE" ]; then
            # For DEV versions: Check if there are newer commits for this addon
            if [[ "$VERSION" == *"-dev"* ]]; then
                if [ -n "$DEV_COMMIT" ]; then
                    # Get latest commit for this addon from GitHub
                    local LATEST_COMMIT
                    LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7)

                    if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
                        UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
                        bashio::log.yellow "   Your commit: $DEV_COMMIT"
                        bashio::log.yellow "   Latest: $LATEST_COMMIT"
                    fi
                fi

                # Also check if a stable release is available
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # Compare versions
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                        bashio::log.yellow "   Consider upgrading to the stable release"
                    fi
                fi

            # For BETA versions (< 1.0.0): Check for newer beta OR stable
            elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # If stable is >= 1.0.0, it's definitely newer
                    local LATEST_MAJOR="${LATEST_STABLE%%.*}"
                    if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                    elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi

            # For STABLE versions: Simple version comparison
            else
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi
            fi
        fi

        if [ -n "$UPDATE_MSG" ]; then
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            bashio::log.yellow "$UPDATE_MSG"
            bashio::log.yellow "   You are running: $VERSION"
            bashio::log.yellow "   Update via the Add-on Store"
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        fi
    fi

    # Footer with links
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info "📝 Issues: https://github.com/$REPO/issues"
    bashio::log.info "💖 Maintained by: $MAINTAINER"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue &>/dev/null 2>&1; then
    _show_startup_banner
fi

# </ADDON_BANNER_INJECTION>








# Enable strict mode
set -e

source /usr/lib/bashio/bashio.sh
# shellcheck disable=SC1091


# Get Addon Version

# Manually load S6 environment to ensure Bashio has access to SUPERVISOR_TOKEN
# This avoids using `with-contenv` which causes PID 1 errors in this context
if [ -d /var/run/s6/container_environment ]; then
	for var in /var/run/s6/container_environment/*; do
		[ -e "$var" ] || continue
		declare -x "$(basename "$var")=$(cat "$var")"
	done
fi

# Define paths
CONFIG_PATH="/data/filebrowser.json"
DB_PATH="/data/database.db"
CERT_DIR="/ssl"

bashio::log.info "🛡️ Starting ShieldFile Addon v1.0.8 (Debug: No-Contenv Mode)..."

# Read Config
CERT_FILE=$(bashio::config 'certfile')
KEY_FILE=$(bashio::config 'keyfile')
PORT=$(bashio::config 'port')
BASE_DIR=$(bashio::config 'base_directory')
LOG_LEVEL=$(bashio::config 'log_level')

# Certificates
FULL_CERT_PATH="${CERT_DIR}/${CERT_FILE}"
FULL_KEY_PATH="${CERT_DIR}/${KEY_FILE}"

if bashio::fs.file_exists "${FULL_CERT_PATH}" && bashio::fs.file_exists "${FULL_KEY_PATH}"; then
	bashio::log.info "  Certificate found: ${FULL_CERT_PATH}"
else
	bashio::log.warning "  Certificate NOT found at ${FULL_CERT_PATH}. Generating Self-Signed..."
	mkdir -p "$(dirname "${FULL_CERT_PATH}")"
	mkdir -p "$(dirname "${FULL_KEY_PATH}")"
	openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 \
		-nodes -keyout "${FULL_KEY_PATH}" -out "${FULL_CERT_PATH}" \
		-subj "/CN=shieldfile-addon" \
		-addext "subjectAltName=DNS:shieldfile-addon,IP:127.0.0.1"
fi

# Initialize DB if missing
if [ ! -f "$DB_PATH" ]; then
	bashio::log.info "📁 Initializing Database at ${DB_PATH}..."
	filebrowser config init --database "$DB_PATH"

	# Set Branding and Password Length
	filebrowser config set --branding.name "ShieldFile" --branding.disableExternal --auth.minPasswordLength 8 --database "$DB_PATH"
else
	bashio::log.info "📁 Database found."
	# Ensure password length is set even if DB already exists but was initialized with 12
	filebrowser config set --auth.minPasswordLength 8 --database "$DB_PATH"
fi

# Add/Update Users
bashio::log.info "👤 Syncing users..."

user_count=0

# Check if users configuration exists and has entries
if bashio::config.has_value 'users'; then
	for user in $(bashio::config 'users|keys'); do
		USERNAME=$(bashio::config "users[${user}].username")
		PASSWORD=$(bashio::config "users[${user}].password")

		# Validate username and password
		if [ -z "$USERNAME" ]; then
			bashio::log.warning "  Skipping user entry ${user}: username is empty"
			continue
		fi

		if [ -z "$PASSWORD" ]; then
			bashio::log.warning "  Skipping user '${USERNAME}': password is empty"
			continue
		fi

		# Check if user already exists
		if filebrowser users find "$USERNAME" --database "$DB_PATH" &>/dev/null; then
			# User exists - update password
			if filebrowser users update "$USERNAME" --password "$PASSWORD" --perm.admin --database "$DB_PATH" 2>/dev/null; then
				bashio::log.info "  Updated user: $USERNAME"
			else
				bashio::log.error "  Failed to update user: $USERNAME"
			fi
		else
			# User does not exist - create new
			if filebrowser users add "$USERNAME" "$PASSWORD" --perm.admin --database "$DB_PATH" 2>/dev/null; then
				bashio::log.info "  Created user: $USERNAME"
			else
				bashio::log.error "  Failed to create user: $USERNAME"
			fi
		fi
		user_count=$((user_count + 1))
	done
fi

# If no users were configured/created, create a default admin user
if [ "$user_count" -eq 0 ]; then
	bashio::log.warning "No users configured in addon settings!"

	# Check if default admin already exists in database
	if filebrowser users find "admin" --database "$DB_PATH" &>/dev/null; then
		bashio::log.info "  Default 'admin' user already exists in database."
	else
		bashio::log.warning "  Creating default user: admin / changeme"
		bashio::log.warning "  ⚠️  PLEASE CHANGE THE DEFAULT PASSWORD!"
		if filebrowser users add "admin" "changeme" --perm.admin --database "$DB_PATH" 2>/dev/null; then
			bashio::log.info "  Default admin user created successfully."
		else
			bashio::log.error "  Failed to create default admin user!"
		fi
	fi
fi

# Start
bashio::log.info "🚀 ShieldFile listening on port ${PORT} (Root: ${BASE_DIR})"

# Construct Args
ARGS=()
ARGS+=("--port" "$PORT")
ARGS+=("--root" "$BASE_DIR")
ARGS+=("--database" "$DB_PATH")
ARGS+=("--cert" "$FULL_CERT_PATH")
ARGS+=("--key" "$FULL_KEY_PATH")
ARGS+=("--address" "0.0.0.0") # Listen on all interfaces (Host Network)

# Run
exec filebrowser "${ARGS[@]}"
