#!/usr/bin/env bashio

# <ADDON_BANNER_INJECTION>

# ============================================================================
# Addon Startup Banner - Auto-generated by CI
# ============================================================================
_show_startup_banner() {
    local VERSION="2.0.0"
    local NAME="OpenSSL"
    local SLUG="openssl"
    local UNSUPPORTED="false"
    local REPO="FaserF/hassio-addons"
    local MAINTAINER="FaserF"

    # Extract base version and commit from dev versions (1.2.3-dev+abc123)
    local BASE_VERSION="${VERSION%%-dev*}"
    local DEV_COMMIT=""
    if [[ "$VERSION" == *"+""*" ]]; then
        DEV_COMMIT="${VERSION##*+}"
    fi

    # Header
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.blue "  🏠 $NAME"
    bashio::log.blue "  📦 Version: $VERSION"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Status indicator
    if [ "$UNSUPPORTED" = "true" ]; then
        bashio::log.error "🚨 STATUS: UNSUPPORTED"
        bashio::log.error "   This addon is no longer maintained!"
    elif [[ "$VERSION" == *"-dev"* ]]; then
        bashio::log.warning "🚧 STATUS: DEVELOPMENT"
        bashio::log.warning "   This is a development build!"
    elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
        bashio::log.notice "🔬 STATUS: BETA"
        bashio::log.notice "   This addon is in beta testing."
    else
        bashio::log.green "✅ STATUS: STABLE"
    fi

    # Helper for semantic version comparison
    version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }

    # ========================================================================
    # Smart Update Check
    # ========================================================================
    if command -v curl &>/dev/null; then
        local UPDATE_MSG=""

        # Get latest stable version from config.yaml
        local LATEST_STABLE
        LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//')

        if [ -n "$LATEST_STABLE" ]; then
            # For DEV versions: Check if there are newer commits for this addon
            if [[ "$VERSION" == *"-dev"* ]]; then
                if [ -n "$DEV_COMMIT" ]; then
                    # Get latest commit for this addon from GitHub
                    local LATEST_COMMIT
                    LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7)

                    if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
                        UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
                        bashio::log.yellow "   Your commit: $DEV_COMMIT"
                        bashio::log.yellow "   Latest: $LATEST_COMMIT"
                    fi
                fi

                # Also check if a stable release is available
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # Compare versions
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                        bashio::log.yellow "   Consider upgrading to the stable release"
                    fi
                fi

            # For BETA versions (< 1.0.0): Check for newer beta OR stable
            elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # If stable is >= 1.0.0, it's definitely newer
                    local LATEST_MAJOR="${LATEST_STABLE%%.*}"
                    if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                    elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi

            # For STABLE versions: Simple version comparison
            else
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi
            fi
        fi

        if [ -n "$UPDATE_MSG" ]; then
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            bashio::log.yellow "$UPDATE_MSG"
            bashio::log.yellow "   You are running: $VERSION"
            bashio::log.yellow "   Update via the Add-on Store"
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        fi
    fi

    # Footer with links
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info "📝 Issues: https://github.com/$REPO/issues"
    bashio::log.info "💖 Maintained by: $MAINTAINER"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue &>/dev/null 2>&1; then
    _show_startup_banner
fi

# </ADDON_BANNER_INJECTION>




# Enable strict mode
set -e
# shellcheck disable=SC1091

# Configuration
website_name=$(bashio::config 'website_name')
key_file=/ssl/key_openssl.pem
cert_file=/ssl/cert_openssl.pem

# Certificate settings
KEY_BITS=4096
VALID_DAYS=10000

bashio::log.info "=============================================="
bashio::log.info "        OpenSSL Certificate Generator         "
bashio::log.info "=============================================="
bashio::log.info ""
bashio::log.info "Configuration:"
bashio::log.info "  Common Name (CN):  ${website_name}"
bashio::log.info "  Key Size:          ${KEY_BITS} bit RSA"
bashio::log.info "  Validity:          ${VALID_DAYS} days (~27 years)"
bashio::log.info "  Key File:          ${key_file}"
bashio::log.info "  Certificate File:  ${cert_file}"
bashio::log.info ""

# Check and remove existing files
if test -f "$key_file"; then
	bashio::log.notice "Existing key file found: ${key_file}"
	bashio::log.notice "Removing old key file..."
	rm "$key_file"
fi

if test -f "$cert_file"; then
	bashio::log.notice "Existing certificate found: ${cert_file}"
	bashio::log.notice "Removing old certificate..."
	rm "$cert_file"
fi

# Generate certificate
bashio::log.info "Generating new self-signed certificate..."
bashio::log.info "(This may take a moment...)"
bashio::log.info ""

# Run openssl with quiet output, redirecting progress to /dev/null
if openssl req -x509 -newkey rsa:${KEY_BITS} -keyout "$key_file" -out "$cert_file" -days ${VALID_DAYS} -nodes -subj "/CN=$website_name" 2>/dev/null; then
	bashio::log.info ""
	bashio::log.info "=============================================="
	bashio::log.info "  ✓ Certificate generated successfully!"
	bashio::log.info "=============================================="
	bashio::log.info ""
	bashio::log.info "Output files:"
	bashio::log.info "  Private Key:   ${key_file}"
	bashio::log.info "  Certificate:   ${cert_file}"
	bashio::log.info ""

	# Show certificate info
	bashio::log.info "Certificate details:"
	cert_info=$(openssl x509 -in "$cert_file" -noout -subject -dates 2>/dev/null || true)
	if [ -n "$cert_info" ]; then
		echo "$cert_info" | while read -r line; do
			bashio::log.info "  $line"
		done
	fi
	bashio::log.info ""
	bashio::log.info "You can now use these files in your Home Assistant configuration."
	bashio::log.info "Example for configuration.yaml:"
	bashio::log.info ""
	bashio::log.info "  http:"
	bashio::log.info "    ssl_certificate: /ssl/cert_openssl.pem"
	bashio::log.info "    ssl_key: /ssl/key_openssl.pem"
	bashio::log.info ""
	bashio::log.info "The add-on will now stop."
else
	bashio::log.error "Failed to generate certificate!"
	exit 1
fi

exit 0
