build_from:
  armhf: "ghcr.io/hassio-addons/base:19.0.0"
  armv7: "ghcr.io/hassio-addons/base:19.0.0"
  aarch64: "ghcr.io/hassio-addons/base:19.0.0"
  amd64: "ghcr.io/hassio-addons/base:19.0.0"
  i386: "ghcr.io/hassio-addons/base:18.2.1"