#!/usr/bin/with-contenv bashio
# shellcheck disable=SC1091
# shellcheck shell=bash

# <ADDON_BANNER_INJECTION>

# ============================================================================
# Addon Startup Banner - Auto-generated by CI
# ============================================================================
_show_startup_banner() {
	local VERSION
	if ! VERSION=$(bashio::addon.version 2>/dev/null); then
		VERSION="unknown"
	fi
	if [ -z "$VERSION" ]; then
		VERSION="unknown"
	fi
	local NAME="Tado Auto Assist"
	local SLUG="tado_aa"
	local UNSUPPORTED="false"
	local MAINTAINER="FaserF"
	local REPO="$MAINTAINER/hassio-addons"

	# Extract base version and commit from dev versions (1.2.3-dev+abc123)
	local BASE_VERSION="${VERSION%%-dev*}"
	local DEV_COMMIT=""
	if [[ "$VERSION" == *"+"* ]]; then
		DEV_COMMIT="${VERSION##*+}"
	fi

	# Status indicator
	if [ "$UNSUPPORTED" = "true" ]; then
		bashio::log.error "🚨 STATUS: UNSUPPORTED"
		bashio::log.error "   This addon is no longer maintained!"
	elif [[ "$VERSION" == *"-dev"* ]]; then
		bashio::log.warning "🚧 STATUS: DEVELOPMENT"
		bashio::log.warning "   This is a development build!"
	elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
		bashio::log.notice "🔬 STATUS: BETA"
		bashio::log.notice "   This addon is in beta testing."
	else
		bashio::log.green "✅ STATUS: STABLE"
	fi

	# Helper for semantic version comparison (Pure Bash)
	# Returns 0 if $1 > $2, 1 otherwise
	version_gt() {
		local v1="$1"
		local v2="$2"
		if [ "$v1" = "$v2" ]; then return 1; fi

		local IFS=.
		local i ver1 ver2
		read -ra ver1 <<<"$v1"
		read -ra ver2 <<<"$v2"

		# Pad with zeros
		for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do ver1[i]=0; done
		for ((i = ${#ver2[@]}; i < ${#ver1[@]}; i++)); do ver2[i]=0; done

		for ((i = 0; i < ${#ver1[@]}; i++)); do
			# Handle non-numeric (e.g. dev versions) by treating as 0
			# Simple sanitization: remove anything not a digit using bash expansion
			local n1="${ver1[i]//[!0-9]/}"
			local n2="${ver2[i]//[!0-9]/}"

			# Fallback (rarely needed if using bash, but harmless to keep if desired,
			# though user suggestion implies we can rely on bash expansion)
			# We will use the bash expansion result directly.

			# Empty string -> 0
			[ -z "$n1" ] && n1=0
			[ -z "$n2" ] && n2=0

			if ((10#$n1 > 10#$n2)); then return 0; fi
			if ((10#$n1 < 10#$n2)); then return 1; fi
		done
		return 1
	}

	# ========================================================================
	# Smart Update Check
	# ========================================================================
	if command -v curl &>/dev/null; then
		local UPDATE_MSG=""

		# Ensure we don't fail on pipe errors
		local LATEST_STABLE=""

		# Get latest stable version from config.yaml
		if LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//'); then
			: # Success
		else
			LATEST_STABLE=""
		fi

		if [ -n "$LATEST_STABLE" ]; then
			# For DEV versions: Check if there are newer commits for this addon
			if [[ "$VERSION" == *"-dev"* ]]; then
				if [ -n "$DEV_COMMIT" ]; then
					# Get latest commit for this addon from GitHub
					local LATEST_COMMIT=""
					if LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7); then
						:
					fi

					if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
						UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
						bashio::log.yellow "   Your commit: $DEV_COMMIT"
						bashio::log.yellow "   Latest: $LATEST_COMMIT"
					fi
				fi

				# Also check if a stable release is available
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# Compare versions
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
						bashio::log.yellow "   Consider upgrading to the stable release"
					fi
				fi

			# For BETA versions (< 1.0.0): Check for newer beta OR stable
			elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# If stable is >= 1.0.0, it's definitely newer
					local LATEST_MAJOR="${LATEST_STABLE%%.*}"
					if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
					elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi

			# For STABLE versions: Simple version comparison
			else
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi
			fi
		fi

		if [ -n "$UPDATE_MSG" ]; then
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
			bashio::log.yellow "$UPDATE_MSG"
			bashio::log.yellow "   You are running: $VERSION"
			bashio::log.yellow "   Update via the Add-on Store"
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
		fi
	fi

	# Footer with links
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info " Add-on: $NAME"
	bashio::log.info " 📝 Issues: https://github.com/$REPO/issues"
	bashio::log.info " 💖 Maintained by: $MAINTAINER"
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue &>/dev/null 2>&1; then
	_show_startup_banner
fi

# </ADDON_BANNER_INJECTION>

# Enable strict mode
set -eo pipefail

username=$(bashio::config 'username')
password=$(bashio::config 'password')
minTemp=$(bashio::config 'minTemp')
maxTemp=$(bashio::config 'maxTemp')
log_level=$(bashio::config 'log_level')

# Validate credentials
if [ -z "$username" ] || [ "$username" = "null" ] || [ -z "$password" ] || [ "$password" = "null" ]; then
	bashio::log.error "=========================================="
	bashio::log.error "❌ Missing Tado credentials!"
	bashio::log.error "=========================================="
	bashio::log.error "Please configure your Tado username and password in the add-on configuration."
	bashio::log.error ""
	bashio::log.error "Required configuration:"
	bashio::log.error "  username: Your Tado email address"
	bashio::log.error "  password: Your Tado password"
	bashio::log.error ""
	bashio::log.error "You can find these settings in the 'Configuration' tab of this add-on."
	bashio::exit.nok
fi

# Check if old/invalid token file exists and warn user
if [ -f /data/refresh_token ]; then
	bashio::log.warning "Found existing refresh token file."
	bashio::log.warning "If you're experiencing login issues, try deleting /data/refresh_token"
	bashio::log.warning "and restarting the add-on to force a fresh login."
fi

export TADO_USERNAME="${username}"
export TADO_PASSWORD="${password}"
export TADO_MIN_TEMP="${minTemp:-5}"
export TADO_MAX_TEMP="${maxTemp:-25}"

source /venv/bin/activate

if python3 -c "import logging" 2>/dev/null; then
	# Map Bashio log levels to Python logging levels
	case "${log_level}" in
	trace | debug) export LOG_LEVEL="DEBUG" ;;
	info | notice) export LOG_LEVEL="INFO" ;;
	warning | warn | minimal) export LOG_LEVEL="WARNING" ;;
	error | fatal) export LOG_LEVEL="ERROR" ;;
	*) export LOG_LEVEL="INFO" ;;
	esac
	bashio::log.info "Setting Python LOG_LEVEL to ${LOG_LEVEL}"
fi

bashio::log.info "Starting Tado Auto Assist python script from adrianslabu/tado_aa"
bashio::log.info "Using username: ${username}"
bashio::log.info "If login fails, please verify:"
bashio::log.info "  1. Your Tado email address is correct"
bashio::log.info "  2. Your Tado password is correct"
bashio::log.info "  3. Your Tado account is active and not locked"
bashio::log.info "  4. If the error persists, delete /data/refresh_token and restart"

if [ "$log_level" != "minimal" ]; then
	exec python3 -u /tado_aa.py
else
	exec python3 /tado_aa.py
fi
