---
name: SNClient
version: v0.29
slug: snclient
description: SNClient+ - Cross platform monitoring agent
url: https://github.com/ConSol-Monitoring/snclient
arch:
  #- aarch64
  - amd64
startup: application
boot: auto
ingress: true
init: false
full_access: true
ports:
  8443/tcp: 8443
ports_description:
  8443/tcp: Webserver to query data


build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
  amd64: ghcr.io/hassio-addons/debiab-base/amd64:stable
  armhf: ghcr.io/hassio-addons/debian-base/armhf:stable
  armv7: ghcr.io/hassio-addons/debian-base/armv7:stable
  i386: ghcr.io/hassio-addons/debian-base/i386:stable
