---
name: SNClient
version: v0.29
slug: snclient
description: SNClient+ - Cross platform monitoring agent
url: https://github.com/ConSol-Monitoring/snclient
arch:
  #- aarch64
  - amd64
startup: application
boot: auto
ingress: true
init: false
full_access: true
ports:
  8443/tcp: 8443
ports_description:
  8443/tcp: Webserver to query data
