import { loadTelegramStore, saveTelegramStore } from '../../whatsapp/telegram/store.js';
import { TelegramBotClient } from '../../whatsapp/telegram/bot.js';

export function registerTelegramRoutes(app) {
  // GET /api/telegram/config
  app.get('/api/telegram/config', (req, res) => {
    const store = loadTelegramStore();
    res.json({ success: true, data: store });
  });

  // POST /api/telegram/config
  app.post('/api/telegram/config', async (req, res) => {
    const store = loadTelegramStore();
    const { enabled } = req.body || {};

    if (enabled !== undefined) {
      store.enabled = Boolean(enabled);
    }

    saveTelegramStore(store);
    res.json({ success: true, data: store });
  });

  // GET /api/telegram/bots
  app.get('/api/telegram/bots', (req, res) => {
    const store = loadTelegramStore();
    res.json({ success: true, data: store.bots || [] });
  });

  // POST /api/telegram/bots
  app.post('/api/telegram/bots', async (req, res) => {
    const store = loadTelegramStore();
    const { id, name, token, enabled } = req.body || {};

    if (!token || !String(token).trim()) {
      return res.status(400).json({ success: false, error: 'Bot token is required' });
    }

    let botInfo;
    let username;
    const cleanToken = String(token).trim();
    try {
      const bot = new TelegramBotClient(cleanToken);
      botInfo = await bot.getMe();
      username = botInfo ? botInfo.username || '' : '';
      const botId = id || `bot_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
      await bot.fetchUpdates(botId);
    } catch (err) {
      return res.status(400).json({ success: false, error: `Invalid Bot Token: ${err.message}` });
    }

    const botId = id || `bot_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
    const botName =
      name && String(name).trim()
        ? String(name).trim()
        : username
          ? `@${username}`
          : 'Telegram Bot';

    const botRecord = {
      id: botId,
      name: botName,
      token: cleanToken,
      username: username,
      info: botInfo,
      enabled: enabled !== undefined ? Boolean(enabled) : true,
    };

    if (!store.bots) store.bots = [];
    const idx = store.bots.findIndex((b) => b.id === botId);
    if (idx >= 0) {
      store.bots[idx] = botRecord;
    } else {
      store.bots.push(botRecord);
    }

    saveTelegramStore(store);
    res.json({ success: true, data: store.bots });
  });

  // DELETE /api/telegram/bots/:id
  app.delete('/api/telegram/bots/:id', (req, res) => {
    const store = loadTelegramStore();
    const { id } = req.params;
    store.bots = (store.bots || []).filter((b) => b.id !== id);
    // Also remove mappings using this bot or unbind them
    if (Array.isArray(store.mappings)) {
      store.mappings = store.mappings.filter((m) => m.bot_id !== id);
    }
    saveTelegramStore(store);
    res.json({ success: true, data: store.bots });
  });

  // GET /api/telegram/chats
  app.get('/api/telegram/chats', async (req, res) => {
    const store = loadTelegramStore();
    const { bot_id } = req.query || {};
    const bots = (store.bots || []).filter((b) => b.enabled && b.token);
    for (const b of bots) {
      if (bot_id && b.id !== bot_id) continue;
      try {
        const bot = new TelegramBotClient(b.token);
        await bot.fetchUpdates(b.id);
      } catch (e) {
        // Ignore fetch updates error
      }
    }
    const updatedStore = loadTelegramStore();
    let chats = Object.values(updatedStore.cached_chats || {});
    if (bot_id) {
      chats = chats.filter((c) => !c.bot_id || c.bot_id === bot_id);
    }
    res.json({ success: true, data: chats });
  });

  // POST /api/telegram/mappings
  app.post('/api/telegram/mappings', (req, res) => {
    const store = loadTelegramStore();
    const {
      id,
      bot_id,
      mapping_name,
      wa_jid,
      wa_name,
      tg_chat_id,
      tg_chat_title,
      tg_chat_type,
      sync_mode,
      include_group_name,
      include_sender_name,
      sync_self_messages,
      tg_thread_id,
      convert_formatting,
      anonymize_phone_numbers,
      ignore_command_prefixes,
      sync_reactions,
      sync_edits,
      sync_deletions,
      is_direct_chat_mirror,
      enabled,
    } = req.body || {};

    if (!wa_jid || !tg_chat_id) {
      return res.status(400).json({ success: false, error: 'Missing wa_jid or tg_chat_id' });
    }

    const firstBotId = (store.bots || [])[0]?.id || '';
    const selectedBotId = bot_id || firstBotId;

    const cleanWaName = wa_name && wa_name !== wa_jid ? wa_name : wa_jid.split('@')[0];
    const cleanTgTitle =
      tg_chat_title && !tg_chat_title.startsWith('Chat ') ? tg_chat_title : `TG ${tg_chat_id}`;
    const threadLabel = tg_thread_id ? ` (Topic ${tg_thread_id})` : '';
    const autoGeneratedName = `${cleanWaName} ↔ ${cleanTgTitle}${threadLabel}`;
    const finalMappingName =
      mapping_name && String(mapping_name).trim() ? String(mapping_name).trim() : autoGeneratedName;

    const mappingId = id || `map_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
    const newMapping = {
      id: mappingId,
      bot_id: selectedBotId,
      name: finalMappingName,
      wa_jid: String(wa_jid),
      wa_name: wa_name || wa_jid,
      tg_chat_id: String(tg_chat_id),
      tg_chat_title: tg_chat_title || `Chat ${tg_chat_id}`,
      tg_chat_type: tg_chat_type || 'group',
      sync_mode: sync_mode || 'bidirectional',
      include_group_name: is_direct_chat_mirror ? false : Boolean(include_group_name),
      include_sender_name: is_direct_chat_mirror
        ? false
        : include_sender_name !== undefined
          ? Boolean(include_sender_name)
          : true,
      sync_self_messages: is_direct_chat_mirror
        ? sync_self_messages !== undefined
          ? Boolean(sync_self_messages)
          : true
        : Boolean(sync_self_messages),
      tg_thread_id: tg_thread_id ? String(tg_thread_id) : null,
      convert_formatting: convert_formatting !== undefined ? Boolean(convert_formatting) : true,
      anonymize_phone_numbers: Boolean(anonymize_phone_numbers),
      ignore_command_prefixes: ignore_command_prefixes ? String(ignore_command_prefixes) : '',
      sync_reactions: sync_reactions !== undefined ? Boolean(sync_reactions) : true,
      sync_edits: sync_edits !== undefined ? Boolean(sync_edits) : true,
      sync_deletions: sync_deletions !== undefined ? Boolean(sync_deletions) : true,
      is_direct_chat_mirror: Boolean(is_direct_chat_mirror),
      enabled: enabled !== undefined ? Boolean(enabled) : true,
    };

    const existingIdx = (store.mappings || []).findIndex((m) => m.id === mappingId);
    if (existingIdx >= 0) {
      store.mappings[existingIdx] = newMapping;
    } else {
      if (!store.mappings) store.mappings = [];
      store.mappings.push(newMapping);
    }

    saveTelegramStore(store);
    res.json({ success: true, data: store.mappings });
  });

  // DELETE /api/telegram/mappings/:id
  app.delete('/api/telegram/mappings/:id', (req, res) => {
    const store = loadTelegramStore();
    const { id } = req.params;
    store.mappings = (store.mappings || []).filter((m) => m.id !== id);
    saveTelegramStore(store);
    res.json({ success: true, data: store.mappings });
  });

  // POST /api/telegram/mappings/:id/toggle
  app.post('/api/telegram/mappings/:id/toggle', (req, res) => {
    const store = loadTelegramStore();
    const { id } = req.params;
    const mapping = (store.mappings || []).find((m) => m.id === id);
    if (!mapping) {
      return res.status(404).json({ success: false, error: 'Mapping not found' });
    }
    mapping.enabled = !mapping.enabled;
    saveTelegramStore(store);
    res.json({ success: true, data: mapping });
  });
}
