build_from:
  armhf: "ghcr.io/hassio-addons/base-python:16.1.4"
  armv7: "ghcr.io/hassio-addons/base-python:16.1.4"
  aarch64: "ghcr.io/hassio-addons/base-python:16.1.4"
  amd64: "ghcr.io/hassio-addons/base-python:16.1.4"
  i386: "ghcr.io/hassio-addons/base-python:16.1.4"
