#!/usr/bin/with-contenv bashio
# shellcheck disable=SC1091
# shellcheck shell=bash
# Source bashio early for banner functions
# Enable strict mode

# <App_BANNER_INJECTION>

# ============================================================================
# App Startup Banner - Auto-generated by CI
# ============================================================================
_show_app_banner() {
	local VERSION
	if ! VERSION=$(bashio::app.version 2>/dev/null); then
		if ! VERSION=$(bashio::addon.version 2>/dev/null); then
			VERSION="unknown"
		fi
	fi
	if [ -z "$VERSION" ]; then
		VERSION="unknown"
	fi
	local NAME="ShieldDNS"
	local GITHUB_PATH="ShieldDNS"
	local UNSUPPORTED="false"
	local MAINTAINER="FaserF"
	local REPO="$MAINTAINER/hassio-addons"

	# Restart Loop Protection (Max 3 consecutive failed starts)
	if [ -z "${_BOOT_LOOP_CHECKED:-}" ] && [ -d "/data" ]; then
		export _BOOT_LOOP_CHECKED=1
		local STATE_FILE="/data/.boot_loop_protection"
		local LAST_VER=""
		local FAIL_COUNT=0

		if [ -f "$STATE_FILE" ]; then
			LAST_VER=$(head -n 1 "$STATE_FILE" 2>/dev/null)
			FAIL_COUNT=$(sed -n '2p' "$STATE_FILE" 2>/dev/null)
			FAIL_COUNT="${FAIL_COUNT//[!0-9]/}"
			[ -z "${FAIL_COUNT:-}" ] && FAIL_COUNT=0
		fi

		if [ "${VERSION:-}" != "${LAST_VER:-}" ]; then
			FAIL_COUNT=0
			LAST_VER="${VERSION:-}"
		fi

		FAIL_COUNT=$((FAIL_COUNT + 1))

		if [ "$FAIL_COUNT" -gt 3 ]; then
			bashio::log.error "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
			bashio::log.error "🚨 RESTART LOOP DETECTED!"
			bashio::log.error "⚠️  This App has failed to start 3 times consecutively."
			bashio::log.error "⚠️  Stopping App to prevent an endless restart loop."
			bashio::log.error "💡 Update the App or fix configuration issues to try again."
			bashio::log.error "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

			printf "%s
0
" "$VERSION" >"$STATE_FILE" 2>/dev/null

			if type bashio::app.stop >/dev/null 2>&1; then
				bashio::app.stop 2>/dev/null || true
			elif type bashio::addon.stop >/dev/null 2>&1; then
				bashio::addon.stop 2>/dev/null || true
			fi
			sleep 3600
			exit 0
		fi

		printf "%s
%s
" "$VERSION" "$FAIL_COUNT" >"$STATE_FILE" 2>/dev/null

		(
			sleep 120
			if [ -d "/data" ]; then
				printf "%s
0
" "$VERSION" >"/data/.boot_loop_protection" 2>/dev/null
			fi
		) &
	fi

	# Extract base version and commit from dev versions (1.2.3-dev+abc123)
	local BASE_VERSION="${VERSION%%-dev*}"
	local DEV_COMMIT=""
	if [[ "$VERSION" == *"+"* ]]; then
		DEV_COMMIT="${VERSION##*+}"
	fi

	# Status indicator
	if [ "$UNSUPPORTED" = "true" ]; then
		bashio::log.error "🚨 STATUS: UNSUPPORTED"
		bashio::log.error "   This App is no longer maintained!"
	elif [[ "$VERSION" == *"-dev"* ]]; then
		bashio::log.warning "🚧 STATUS: DEVELOPMENT"
		bashio::log.warning "   This is a development build!"
	elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
		bashio::log.notice "🔬 STATUS: BETA"
		bashio::log.notice "   This App is in beta testing."
	else
		bashio::log.green "✅ STATUS: STABLE"
	fi

	# Helper for semantic version comparison (Pure Bash)
	# Returns 0 if $1 > $2, 1 otherwise
	version_gt() {
		local v1="$1"
		local v2="$2"
		if [ "$v1" = "$v2" ]; then return 1; fi

		local IFS=.
		local i ver1 ver2
		read -ra ver1 <<<"$v1"
		read -ra ver2 <<<"$v2"

		# Pad with zeros
		for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do ver1[i]=0; done
		for ((i = ${#ver2[@]}; i < ${#ver1[@]}; i++)); do ver2[i]=0; done

		for ((i = 0; i < ${#ver1[@]}; i++)); do
			# Handle non-numeric (e.g. dev versions) by treating as 0
			# Simple sanitization: remove anything not a digit using bash expansion
			local n1="${ver1[i]//[!0-9]/}"
			local n2="${ver2[i]//[!0-9]/}"

			# Empty string -> 0
			[ -z "$n1" ] && n1=0
			[ -z "$n2" ] && n2=0

			if ((10#$n1 > 10#$n2)); then return 0; fi
			if ((10#$n1 < 10#$n2)); then return 1; fi
		done
		return 1
	}

	# ========================================================================
	# Smart Update Check
	# ========================================================================
	if command -v curl >/dev/null 2>&1; then
		local UPDATE_MSG=""

		# Ensure we don't fail on pipe errors
		local LATEST_STABLE=""

		# Get latest stable version from config.yaml
		if LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$GITHUB_PATH/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//'); then
			: # Success
		else
			LATEST_STABLE=""
		fi

		if [ -n "$LATEST_STABLE" ]; then
			# For DEV versions: Check if there are newer commits for this App
			if [[ "$VERSION" == *"-dev"* ]]; then
				if [ -n "$DEV_COMMIT" ]; then
					# Get latest commit for this App from GitHub
					local LATEST_COMMIT=""
					if LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$GITHUB_PATH&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7); then
						:
					fi

					if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
						UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
						bashio::log.yellow "   Your commit: $DEV_COMMIT"
						bashio::log.yellow "   Latest: $LATEST_COMMIT"
					fi
				fi

				# Also check if a stable release is available
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# Compare versions
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
						bashio::log.yellow "   Consider upgrading to the stable release"
					fi
				fi

			# For BETA versions (< 1.0.0): Check for newer beta OR stable
			elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# If stable is >= 1.0.0, it's definitely newer
					local LATEST_MAJOR="${LATEST_STABLE%%.*}"
					if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
					elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi

			# For STABLE versions: Simple version comparison
			else
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi
			fi
		fi

		if [ -n "$UPDATE_MSG" ]; then
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
			bashio::log.yellow "$UPDATE_MSG"
			bashio::log.yellow "   You are running: $VERSION"
			bashio::log.yellow "   Update via the App Store"
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
		fi
	fi

	# Footer with links
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info " App: $NAME"
	bashio::log.info " 📝 Issues: https://github.com/$REPO/issues"
	bashio::log.info " 💖 Maintained by: $MAINTAINER"
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue >/dev/null 2>&1; then
	_show_app_banner
fi

# </App_BANNER_INJECTION>

set -e

# Define local paths
COREFILE_PATH="/data/Corefile"

echo "➡️  Starting ShieldDNS Initialization..."

# ------------------------------------------------------------------------------
# 1. Environment Detection & Configuration
# ------------------------------------------------------------------------------
if [ -f "/data/options.json" ] && [ -n "$(command -v bashio::config)" ]; then
	bashio::log.info "ℹ️  Home Assistant Addon environment detected."

	CERT_FILE=$(bashio::config 'certfile')
	KEY_FILE=$(bashio::config 'keyfile')
	if ! LOG_LEVEL=$(bashio::config 'log_level') || [ -z "$LOG_LEVEL" ]; then
		bashio::log.warning "Failed to fetch log_level configuration. Using default: info"
		LOG_LEVEL="info"
	fi
	bashio::log.level "${LOG_LEVEL}"
	DOT_PORT=$(bashio::config 'dot_port')
	DOH_PORT=$(bashio::config 'doh_port')
	export DATA_DIR="/data"

	# Prepend /ssl/ to cert paths if they are just filenames
	if [[ "$CERT_FILE" != /* ]]; then CERT_FILE="/ssl/$CERT_FILE"; fi
	if [[ "$KEY_FILE" != /* ]]; then KEY_FILE="/ssl/$KEY_FILE"; fi
else
	echo "ℹ️  Standard Docker environment detected."
	CERT_FILE=${CERT_FILE:-"/ssl/fullchain.pem"}
	KEY_FILE=${KEY_FILE:-"/ssl/privkey.pem"}
	LOG_LEVEL=${LOG_LEVEL:-"info"}
	DOT_PORT=${DOT_PORT:-853}
	DOH_PORT=${DOH_PORT:-443}
fi

# ------------------------------------------------------------------------------
# 1.5. SSL Fallback Check
# ------------------------------------------------------------------------------
if [ ! -f "$CERT_FILE" ] || [ ! -f "$KEY_FILE" ]; then
	bashio::log.warning "⚠️  WARNING: SSL Certificates not found at ${CERT_FILE} or ${KEY_FILE}!"
	bashio::log.info "⚙️  Generating self-signed fallback certificate..."

	mkdir -p /data/ssl
	FALLBACK_CERT="/data/ssl/selfsigned.crt"
	FALLBACK_KEY="/data/ssl/selfsigned.key"

	if [ ! -f "$FALLBACK_CERT" ]; then
		openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
			-keyout "$FALLBACK_KEY" -out "$FALLBACK_CERT" \
			-subj "/C=DE/ST=ShieldDNS/L=ShieldDNS/O=ShieldDNS/OU=ShieldDNS/CN=shielddns.local" \
			2>/dev/null
	fi

	CERT_FILE="$FALLBACK_CERT"
	KEY_FILE="$FALLBACK_KEY"
	bashio::log.info "✅  ShieldDNS will continue with self-signed certificates (Insecure)."
fi

# ------------------------------------------------------------------------------
# 2. Port Conflict & Availability Checks
# ------------------------------------------------------------------------------
is_port_busy() {
	local PORT=$1
	if [ -n "$PORT" ] && [ "$PORT" != "null" ]; then
		if nc -z 127.0.0.1 "$PORT" 2>/dev/null; then return 0; fi
	fi
	return 1
}

DNS_PORT="53"
if is_port_busy "${DNS_PORT}"; then
	echo "⚠️  Port 53 is BUSY. Switching DNS to Fallback Port: 10053"
	DNS_PORT="10053"
fi

if is_port_busy "${DOT_PORT}"; then
	if [ "${DOT_PORT}" = "853" ]; then
		bashio::log.warning "⚠️  Port 853 is BUSY. Switching DoT to Fallback Port: 8853"
		DOT_PORT="8853"
	fi
fi

if is_port_busy "${DOH_PORT}"; then
	if [ "${DOH_PORT}" = "443" ]; then
		bashio::log.warning "⚠️  Port 443 is BUSY. Switching DoH to Fallback Port: 3443"
		DOH_PORT="3443"
	fi
fi

# ------------------------------------------------------------------------------
# 3. Port Configuration (DoH + Admin UI)
# ------------------------------------------------------------------------------
bashio::log.info "🌍 Unifying DoH and Admin UI on Port ${DOH_PORT}..."
bashio::log.info "🔗 Ingress (Home Assistant) active on Port 8099 (Plain HTTP)"

# ------------------------------------------------------------------------------
# 3.5. Developer Mode (Download and Compile Latest Code from GitHub)
# ------------------------------------------------------------------------------
if bashio::config.true 'developer_mode'; then
	bashio::log.warning "=================================================="
	bashio::log.warning "   ⚠️  DEVELOPER MODE ENABLED  ⚠️"
	bashio::log.warning "=================================================="
	bashio::log.warning "Using latest code from GitHub 'main' branch."
	bashio::log.warning "Downloading and recompiling ShieldDNS Admin..."

	GITHUB_TOKEN=""
	if bashio::config.has_value 'github_token'; then
		TOKEN_VALUE=$(bashio::config 'github_token')
		TOKEN_VALUE=$(echo "$TOKEN_VALUE" | xargs)
		if [ -n "$TOKEN_VALUE" ] && [ "$TOKEN_VALUE" != "null" ]; then
			GITHUB_TOKEN="$TOKEN_VALUE"
		fi
	fi

	DEV_BUILD_DIR="/tmp/shielddns-dev-build"
	rm -rf "$DEV_BUILD_DIR"
	mkdir -p "$DEV_BUILD_DIR"
	cd "$DEV_BUILD_DIR" || exit 1

	download_dev_code() {
		local BRANCH=$1
		local URL="https://github.com/FaserF/ShieldDNS/archive/refs/heads/${BRANCH}.tar.gz"
		local CURL_ARGS=("-fL" "-s" "-S")

		if [ -n "$GITHUB_TOKEN" ]; then
			bashio::log.info "Using GitHub Token for authentication..."
			echo "Authorization: token ${GITHUB_TOKEN}" >/tmp/gh_token_header
			CURL_ARGS+=("-H" "@/tmp/gh_token_header")
		fi

		bashio::log.info "Attempting to download branch: ${BRANCH}"
		if curl "${CURL_ARGS[@]}" "$URL" -o dev_source.tar.gz; then
			rm -f /tmp/gh_token_header
			return 0
		else
			rm -f /tmp/gh_token_header
			return 1
		fi
	}

	if download_dev_code "main" || download_dev_code "master"; then
		bashio::log.info "Extracting ShieldDNS source code..."
		if tar -xzf dev_source.tar.gz --strip-components=1; then
			if [ -d "$DEV_BUILD_DIR/admin" ]; then
				bashio::log.info "Compiling ShieldDNS Admin binary..."
				cd "$DEV_BUILD_DIR/admin" || exit 1
				if go build -o /usr/bin/shielddns-admin .; then
					chmod +x /usr/bin/shielddns-admin
					bashio::log.info "=================================================="
					bashio::log.info "   ✅ DEV MODE COMPILE COMPLETE"
					bashio::log.info "=================================================="
				else
					bashio::log.error "Go compilation failed! Keeping existing binary."
				fi
			else
				bashio::log.error "Admin directory not found in downloaded repository!"
			fi
		else
			bashio::log.error "Failed to extract downloaded repository archive!"
		fi
	else
		bashio::log.error "Failed to download repository from GitHub!"
	fi

	# Clean up
	cd / || exit 1
	rm -rf "$DEV_BUILD_DIR"
fi

# ------------------------------------------------------------------------------
# 4. ShieldDNS Admin & CoreDNS Execution
# ------------------------------------------------------------------------------
mkdir -p /data

# Dynamically set GOMAXPROCS to match the available CPU count.
GOMAXPROCS=$(nproc 2>/dev/null || echo 1)
export GOMAXPROCS

# Export for Go backend
export CERT_FILE
export KEY_FILE
export ADMIN_PORT=${DOH_PORT}
export INGRESS_PORT=8099
export DNS_PORT
export DOT_PORT

# Run integration manager (install/update integration)
/usr/bin/shielddns_integration.sh || true

# Start the unified ShieldDNS Admin backend
# It will listen on:
# - :$ADMIN_PORT (TLS) for DoH and Admin UI
# - :8099 (Plain HTTP) for HA Ingress
/usr/bin/shielddns-admin &
ADMIN_PID=$!

# Give services a moment to start
sleep 2

# Check if services are still running
if ! kill -0 $ADMIN_PID 2>/dev/null; then
	bashio::log.error "❌ ShieldDNS Admin failed to start. Check logs."
	exit 1
fi

bashio::log.info "✅ ShieldDNS Started Successfully."

# Initial Corefile (if backend hasn't generated one yet)
if [ ! -f "$COREFILE_PATH" ]; then
	cat <<EOF >$COREFILE_PATH
.:${DNS_PORT} {
    bind 0.0.0.0
    forward . 1.1.1.1 8.8.8.8
    log
    errors
}
tls://.:${DOT_PORT} {
    tls ${CERT_FILE} ${KEY_FILE}
    forward . 1.1.1.1 8.8.8.8
    log
    errors
}
https://.:${ADMIN_PORT} {
    tls ${CERT_FILE} ${KEY_FILE}
    forward . 1.1.1.1 8.8.8.8
    log
    errors
}
EOF
fi

# CoreDNS is managed by the Go backend (shielddns-admin)
# so it handles log parsing and restarts automatically.

wait $ADMIN_PID
bashio::log.info "⏹️  Shutting down services..."
bashio::log.info "ℹ️  ShieldDNS has stopped."
exit 0
