#!/usr/bin/with-contenv bashio
# shellcheck disable=SC1091
# shellcheck shell=bash
# Source bashio early for banner functions

# <App_BANNER_INJECTION>

# ============================================================================
# App Startup Banner - Auto-generated by CI
# ============================================================================
_show_app_banner() {
	local VERSION
	if ! VERSION=$(bashio::app.version 2>/dev/null); then
		if ! VERSION=$(bashio::addon.version 2>/dev/null); then
			VERSION="unknown"
		fi
	fi
	if [ -z "$VERSION" ]; then
		VERSION="unknown"
	fi
	local NAME="ShieldDNS"
	local SLUG="shielddns"
	local UNSUPPORTED="false"
	local MAINTAINER="FaserF"
	local REPO="$MAINTAINER/hassio-addons"

	# Extract base version and commit from dev versions (1.2.3-dev+abc123)
	local BASE_VERSION="${VERSION%%-dev*}"
	local DEV_COMMIT=""
	if [[ "$VERSION" == *"+"* ]]; then
		DEV_COMMIT="${VERSION##*+}"
	fi

	# Status indicator
	if [ "$UNSUPPORTED" = "true" ]; then
		bashio::log.error "🚨 STATUS: UNSUPPORTED"
		bashio::log.error "   This App is no longer maintained!"
	elif [[ "$VERSION" == *"-dev"* ]]; then
		bashio::log.warning "🚧 STATUS: DEVELOPMENT"
		bashio::log.warning "   This is a development build!"
	elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
		bashio::log.notice "🔬 STATUS: BETA"
		bashio::log.notice "   This App is in beta testing."
	else
		bashio::log.green "✅ STATUS: STABLE"
	fi

	# Helper for semantic version comparison (Pure Bash)
	# Returns 0 if $1 > $2, 1 otherwise
	version_gt() {
		local v1="$1"
		local v2="$2"
		if [ "$v1" = "$v2" ]; then return 1; fi

		local IFS=.
		local i ver1 ver2
		read -ra ver1 <<<"$v1"
		read -ra ver2 <<<"$v2"

		# Pad with zeros
		for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do ver1[i]=0; done
		for ((i = ${#ver2[@]}; i < ${#ver1[@]}; i++)); do ver2[i]=0; done

		for ((i = 0; i < ${#ver1[@]}; i++)); do
			# Handle non-numeric (e.g. dev versions) by treating as 0
			# Simple sanitization: remove anything not a digit using bash expansion
			local n1="${ver1[i]//[!0-9]/}"
			local n2="${ver2[i]//[!0-9]/}"

			# Empty string -> 0
			[ -z "$n1" ] && n1=0
			[ -z "$n2" ] && n2=0

			if ((10#$n1 > 10#$n2)); then return 0; fi
			if ((10#$n1 < 10#$n2)); then return 1; fi
		done
		return 1
	}

	# ========================================================================
	# Smart Update Check
	# ========================================================================
	if command -v curl >/dev/null 2>&1; then
		local UPDATE_MSG=""

		# Ensure we don't fail on pipe errors
		local LATEST_STABLE=""

		# Get latest stable version from config.yaml
		if LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//'); then
			: # Success
		else
			LATEST_STABLE=""
		fi

		if [ -n "$LATEST_STABLE" ]; then
			# For DEV versions: Check if there are newer commits for this App
			if [[ "$VERSION" == *"-dev"* ]]; then
				if [ -n "$DEV_COMMIT" ]; then
					# Get latest commit for this App from GitHub
					local LATEST_COMMIT=""
					if LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7); then
						:
					fi

					if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
						UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
						bashio::log.yellow "   Your commit: $DEV_COMMIT"
						bashio::log.yellow "   Latest: $LATEST_COMMIT"
					fi
				fi

				# Also check if a stable release is available
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# Compare versions
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
						bashio::log.yellow "   Consider upgrading to the stable release"
					fi
				fi

			# For BETA versions (< 1.0.0): Check for newer beta OR stable
			elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					# If stable is >= 1.0.0, it's definitely newer
					local LATEST_MAJOR="${LATEST_STABLE%%.*}"
					if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
					elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi

			# For STABLE versions: Simple version comparison
			else
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi
			fi
		fi

		if [ -n "$UPDATE_MSG" ]; then
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
			bashio::log.yellow "$UPDATE_MSG"
			bashio::log.yellow "   You are running: $VERSION"
			bashio::log.yellow "   Update via the App Store"
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
		fi
	fi

	# Footer with links
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info " App: $NAME"
	bashio::log.info " 📝 Issues: https://github.com/$REPO/issues"
	bashio::log.info " 💖 Maintained by: $MAINTAINER"
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue >/dev/null 2>&1; then
	_show_app_banner
fi

# </App_BANNER_INJECTION>

[ -f /usr/lib/bashio/bashio.sh ] && source /usr/lib/bashio/bashio.sh

# Enable strict mode
set -e

# Define local paths
COREFILE_PATH="/etc/Corefile"

echo "➡️  Starting ShieldDNS Initialization..."

# ------------------------------------------------------------------------------
# 1. Environment Detection & Configuration
# ------------------------------------------------------------------------------
if [ -f "/data/options.json" ] && [ -n "$(command -v bashio::config)" ]; then
	bashio::log.info "ℹ️  Home Assistant Addon environment detected."

	UPSTREAM_DNS=$(bashio::config 'upstream_dns')
	UPSTREAM_DOT=$(bashio::config 'upstream_dot')
	PREFER_ENCRYPTED=$(bashio::config 'prefer_encrypted')
	CERT_FILE=$(bashio::config 'certfile')
	KEY_FILE=$(bashio::config 'keyfile')
	LOG_LEVEL=$(bashio::config 'log_level')
	DOT_PORT=$(bashio::config 'dot_port')
	DOH_PORT=$(bashio::config 'doh_port')
	FALLBACK_DNS_ENABLED=$(bashio::config 'fallback_dns')
	FALLBACK_DNS_SERVER=$(bashio::config 'fallback_dns_server')

	# Prepend /ssl/ to cert paths if they are just filenames
	if [[ "$CERT_FILE" != /* ]]; then CERT_FILE="/ssl/$CERT_FILE"; fi
	if [[ "$KEY_FILE" != /* ]]; then KEY_FILE="/ssl/$KEY_FILE"; fi
else
	echo "ℹ️  Standard Docker environment detected."
	UPSTREAM_DNS=${UPSTREAM_DNS:-"86.54.11.100 1.1.1.1 9.9.9.9 8.8.8.8 1.0.0.1"}
	UPSTREAM_DOT=${UPSTREAM_DOT:-"unfiltered.joindns4.eu dns.quad9.net one.one.one.one dns.google"}
	PREFER_ENCRYPTED=${PREFER_ENCRYPTED:-"true"}
	CERT_FILE=${CERT_FILE:-"/ssl/fullchain.pem"}
	KEY_FILE=${KEY_FILE:-"/ssl/privkey.pem"}
	LOG_LEVEL=${LOG_LEVEL:-"info"}
	DOT_PORT=${DOT_PORT:-853}
	DOH_PORT=${DOH_PORT:-443}
	FALLBACK_DNS_ENABLED=${FALLBACK_DNS_ENABLED:-"false"}
	FALLBACK_DNS_SERVER=${FALLBACK_DNS_SERVER:-"1.1.1.1"}
fi

# Sanitize upstreams (replace commas with spaces)
UPSTREAM_DNS=$(echo "${UPSTREAM_DNS}" | tr ',' ' ')
UPSTREAM_DOT=$(echo "${UPSTREAM_DOT}" | tr ',' ' ')

# ------------------------------------------------------------------------------
# 1.5. SSL Fallback Check
# ------------------------------------------------------------------------------
if [ ! -f "$CERT_FILE" ] || [ ! -f "$KEY_FILE" ]; then
	bashio::log.warning "⚠️  WARNING: SSL Certificates not found at ${CERT_FILE} or ${KEY_FILE}!"
	bashio::log.info "⚙️  Generating self-signed fallback certificate..."

	mkdir -p /etc/shielddns/ssl
	FALLBACK_CERT="/etc/shielddns/ssl/selfsigned.crt"
	FALLBACK_KEY="/etc/shielddns/ssl/selfsigned.key"

	if [ ! -f "$FALLBACK_CERT" ]; then
		openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
			-keyout "$FALLBACK_KEY" -out "$FALLBACK_CERT" \
			-subj "/C=DE/ST=ShieldDNS/L=ShieldDNS/O=ShieldDNS/OU=ShieldDNS/CN=shielddns.local" \
			2>/dev/null
	fi

	CERT_FILE="$FALLBACK_CERT"
	KEY_FILE="$FALLBACK_KEY"
	bashio::log.info "✅  ShieldDNS will continue with self-signed certificates (Insecure)."
fi

# ------------------------------------------------------------------------------
# 2. Port Conflict & Availability Checks
# ------------------------------------------------------------------------------
is_port_busy() {
	local PORT=$1
	if [ -n "$PORT" ] && [ "$PORT" != "null" ]; then
		if nc -z 127.0.0.1 "$PORT" 2>/dev/null; then return 0; fi
	fi
	return 1
}

if is_port_busy "${DOT_PORT}"; then
	if [ "${DOT_PORT}" = "853" ]; then
		bashio::log.warning "⚠️  Port 853 is BUSY. Switching DoT to Fallback Port: 8853"
		DOT_PORT="8853"
	fi
fi

# ------------------------------------------------------------------------------
# 3. Multiplexed Port 443 Configuration (DoH + Admin UI)
# ------------------------------------------------------------------------------
INTERNAL_DOH_PORT="5553"
ADMIN_BACKEND_PORT="8080"

bashio::log.info "🌍 Unifying DoH and Admin UI on Port ${DOH_PORT} (multiplexed via Nginx)..."

mkdir -p /run/nginx /etc/nginx/http.d

cat <<EOF >/etc/nginx/http.d/default.conf
server {
    listen 80;
    server_name _;
    
    location / {
        proxy_pass http://127.0.0.1:${ADMIN_BACKEND_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}

server {
    listen ${DOH_PORT} ssl;
    http2 on;
    server_name _;

    ssl_certificate ${CERT_FILE};
    ssl_certificate_key ${KEY_FILE};
    ssl_protocols TLSv1.2 TLSv1.3;

    error_log /dev/stderr info;
    access_log /dev/stdout;

    location /dns-query {
        proxy_pass https://127.0.0.1:${INTERNAL_DOH_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_ssl_verify off;
    }

    location / {
        proxy_pass http://127.0.0.1:${ADMIN_BACKEND_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # SSE optimization
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 24h;
        gzip off;
    }
}
EOF

nginx -g 'daemon off;' &
NGINX_PID=$!

# ------------------------------------------------------------------------------
# 4. ShieldDNS Admin & CoreDNS Execution
# ------------------------------------------------------------------------------
mkdir -p /etc/shielddns /var/www/admin

# Dynamically set GOMAXPROCS to match the available CPU count.
GOMAXPROCS=$(nproc 2>/dev/null || echo 1)
export GOMAXPROCS

# Export for Go backend
export CERT_FILE
export KEY_FILE
export INTERNAL_DOH_PORT
export ADMIN_PORT=${ADMIN_BACKEND_PORT}

/usr/bin/shielddns-admin &
ADMIN_PID=$!

# Initial Corefile (if backend hasn't generated one yet)
ACTUAL_COREDNS_PORT="${INTERNAL_DOH_PORT}"
if [ ! -f "$COREFILE_PATH" ]; then
	cat <<EOF >$COREFILE_PATH
.:53 {
    bind 0.0.0.0
    forward . ${UPSTREAM_DNS}
    log
    errors
}
tls://.:853 {
    tls ${CERT_FILE} ${KEY_FILE}
    forward . ${UPSTREAM_DNS}
    log
    errors
}
https://.:${ACTUAL_COREDNS_PORT} {
    tls ${CERT_FILE} ${KEY_FILE}
    forward . ${UPSTREAM_DNS}
    log
    errors
}
EOF
fi

# CoreDNS is managed by the Go backend (shielddns-admin)
# so it handles log parsing and restarts automatically.

wait -n $ADMIN_PID $NGINX_PID
bashio::log.info "⏹️  Shutting down services..."
# Kill all background jobs gracefully
mapfile -t PIDS < <(jobs -p)
if [ ${#PIDS[@]} -gt 0 ]; then
	kill -TERM "${PIDS[@]}" 2>/dev/null || true
fi
bashio::log.info "ℹ️  ShieldDNS has stopped."
exit 0
