---
# Pin to specific version for reproducible builds (CodeRabbit: reproducible builds)
build_from:
  aarch64: "ghcr.io/home-assistant/home-assistant:2026.1.3"
  amd64: "ghcr.io/home-assistant/home-assistant:2026.1.3"
