name: "Home Assistant Test Instance (Edge)"
version: "1.0.1-dev-20260722-1742-0d526e2"
slug: "ha_test_instance"
description: "A standalone Home Assistant Core instance for testing purposes."
url: "https://github.com/home-assistant/home-assistant"
arch:
  - aarch64
  - amd64
ports:
  8123/tcp: 18124
map:
  - homeassistant_config:rw
ingress: true
ingress_port: 8123
hassio_api: true
init: false
options:
  log_level: "info"
  copy_host_data: false
  enable_automations: false
schema:
  log_level: list(trace|debug|info|warning|error|fatal)
  copy_host_data: bool?
  enable_automations: bool?
stage: experimental
