---
name: EntraMirror (Edge)
version: "0.1.1"
slug: entramirror
description: Microsoft Entra ID Tenant Backup, Restore, Synchronization & Cloning for Home Assistant.
url: https://github.com/FaserF/EntraMirror
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 8094
ingress_stream: true
panel_icon: mdi:cloud-sync
startup: services

ports:
  8094/tcp: 18094
ports_description:
  8094/tcp: Web Interface (HTTP)
map:
  - homeassistant_config:rw
  - share:rw
options:
  version: "latest"
  github_token: ""
  github_repo: "FaserF/EntraMirror"
  developer_mode: false
  reset_database: false
  log_level: "info"
  secret_key: ""
  debug: false
  sso_enabled: false
  sso_client_id: ""
  sso_tenant_id: "common"

schema:
  version: str
  github_token: password?
  github_repo: str?
  developer_mode: bool
  reset_database: bool
  reset_database_confirm: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  secret_key: password?
  debug: bool?
  sso_enabled: bool?
  sso_client_id: str?
  sso_tenant_id: str?
  first_admin_password: password?
stage: experimental
