#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
# Load custom bashio libraries
# shellcheck source=/dev/null

export PATH="/usr/local/bin:/root/.local/bin:$PATH"

# <App_BANNER_INJECTION>

# ============================================================================
# App Startup Banner - Auto-generated by CI
# ============================================================================
_show_app_banner() {
	local VERSION
	if ! VERSION=$(bashio::app.version 2>/dev/null); then
		if ! VERSION=$(bashio::addon.version 2>/dev/null); then
			VERSION="unknown"
		fi
	fi
	if [ -z "$VERSION" ]; then
		VERSION="unknown"
	fi
	local NAME="EntraMirror"
	local GITHUB_PATH="EntraMirror"
	local UNSUPPORTED="false"
	local MAINTAINER="FaserF"
	local REPO="$MAINTAINER/hassio-addons"

	# Restart Loop Protection (Max 3 consecutive failed starts)
	if [ -z "${_BOOT_LOOP_CHECKED:-}" ] && [ -d "/data" ]; then
		export _BOOT_LOOP_CHECKED=1
		local STATE_FILE="/data/.boot_loop_protection"
		local LAST_VER=""
		local FAIL_COUNT=0

		if [ -f "$STATE_FILE" ]; then
			LAST_VER=$(head -n 1 "$STATE_FILE" 2>/dev/null)
			FAIL_COUNT=$(sed -n '2p' "$STATE_FILE" 2>/dev/null)
			FAIL_COUNT="${FAIL_COUNT//[!0-9]/}"
			[ -z "${FAIL_COUNT:-}" ] && FAIL_COUNT=0
		fi

		if [ "${VERSION:-}" != "${LAST_VER:-}" ]; then
			FAIL_COUNT=0
			LAST_VER="${VERSION:-}"
		fi

		FAIL_COUNT=$((FAIL_COUNT + 1))

		if [ "$FAIL_COUNT" -gt 3 ]; then
			bashio::log.error "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
			bashio::log.error "🚨 RESTART LOOP DETECTED!"
			bashio::log.error "⚠️  This App has failed to start 3 times consecutively."
			bashio::log.error "⚠️  Stopping App to prevent an endless restart loop."
			bashio::log.error "💡 Update the App or fix configuration issues to try again."
			bashio::log.error "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

			printf "%s\n0\n" "$VERSION" >"$STATE_FILE" 2>/dev/null

			if type bashio::addon.stop >/dev/null 2>&1; then
				bashio::addon.stop 2>/dev/null || true
			elif type bashio::app.stop >/dev/null 2>&1; then
				bashio::app.stop 2>/dev/null || true
			fi
			sleep 3600
			exit 0
		fi

		printf "%s\n%s\n" "$VERSION" "$FAIL_COUNT" >"$STATE_FILE" 2>/dev/null

		(
			sleep 120
			if [ -d "/data" ]; then
				printf "%s\n0\n" "$VERSION" >"/data/.boot_loop_protection" 2>/dev/null
			fi
		) &
	fi

	# Extract base version and commit from dev versions (1.2.3-dev+abc123)
	local BASE_VERSION="${VERSION%%-dev*}"
	local DEV_COMMIT=""
	if [[ "$VERSION" == *"+"* ]]; then
		DEV_COMMIT="${VERSION##*+}"
	fi

	# Status indicator
	if [ "$UNSUPPORTED" = "true" ]; then
		bashio::log.error "🚨 STATUS: UNSUPPORTED"
		bashio::log.error "   This App is no longer maintained!"
	elif [[ "$VERSION" == *"-dev"* ]]; then
		bashio::log.warning "🚧 STATUS: DEVELOPMENT"
		bashio::log.warning "   This is a development build!"
	elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
		bashio::log.notice "🔬 STATUS: BETA"
		bashio::log.notice "   This App is in beta testing."
	else
		bashio::log.green "✅ STATUS: STABLE"
	fi

	# Helper for semantic version comparison (Pure Bash)
	version_gt() {
		local v1="$1"
		local v2="$2"
		if [ "$v1" = "$v2" ]; then return 1; fi

		local IFS=.
		local i ver1 ver2
		read -ra ver1 <<<"$v1"
		read -ra ver2 <<<"$v2"

		for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do ver1[i]=0; done
		for ((i = ${#ver2[@]}; i < ${#ver1[@]}; i++)); do ver2[i]=0; done

		for ((i = 0; i < ${#ver1[@]}; i++)); do
			local n1="${ver1[i]//[!0-9]/}"
			local n2="${ver2[i]//[!0-9]/}"

			[ -z "$n1" ] && n1=0
			[ -z "$n2" ] && n2=0

			if ((10#$n1 > 10#$n2)); then return 0; fi
			if ((10#$n1 < 10#$n2)); then return 1; fi
		done
		return 1
	}

	# ========================================================================
	# Smart Update Check
	# ========================================================================
	if command -v curl >/dev/null 2>&1; then
		local UPDATE_MSG=""
		local LATEST_STABLE=""

		if LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$GITHUB_PATH/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//'); then
			:
		else
			LATEST_STABLE=""
		fi

		if [ -n "$LATEST_STABLE" ]; then
			if [[ "$VERSION" == *"-dev"* ]]; then
				if [ -n "$DEV_COMMIT" ]; then
					local LATEST_COMMIT=""
					if LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$GITHUB_PATH&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7); then
						:
					fi

					if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
						UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
						bashio::log.yellow "   Your commit: $DEV_COMMIT"
						bashio::log.yellow "   Latest: $LATEST_COMMIT"
					fi
				fi

				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
						bashio::log.yellow "   Consider upgrading to the stable release"
					fi
				fi

			elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					local LATEST_MAJOR="${LATEST_STABLE%%.*}"
					if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
						UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
					elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi
			else
				if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
					if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
						UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
					fi
				fi
			fi
		fi

		if [ -n "$UPDATE_MSG" ]; then
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
			bashio::log.yellow "$UPDATE_MSG"
			bashio::log.yellow "   You are running: $VERSION"
			bashio::log.yellow "   Update via the App Store"
			bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
		fi
	fi

	# Footer with links
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info " App: $NAME"
	bashio::log.info " 📝 Issues: https://github.com/$REPO/issues"
	bashio::log.info " 💖 Maintained by: $MAINTAINER"
	bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue >/dev/null 2>&1; then
	_show_app_banner
fi

# </App_BANNER_INJECTION>

. /usr/lib/bashio/app.sh
# Enable strict mode
set -e
# shellcheck disable=SC1091

# --- CONFIGURATION ---
DATA_DIR="/data"
DB_DIR="$DATA_DIR"
SNAPSHOTS_DIR="$DATA_DIR/snapshots"
SECRETS_DIR="$DATA_DIR/secrets"

bashio::log.info "Starting EntraMirror App initialization..."

# --- FACTORY RESET CHECK (DANGEROUS!) ---
if bashio::config.true 'reset_database'; then
	if ! bashio::config.true 'reset_database_confirm'; then
		bashio::log.error "Database reset requires both 'reset_database' and 'reset_database_confirm' to be enabled!"
		bashio::log.error "This is a DESTRUCTIVE operation that will DELETE ALL DATA!"
		bashio::log.error "Set 'reset_database_confirm: true' in your configuration to proceed."
		exit 1
	fi

	bashio::log.warning "=================================================="
	bashio::log.warning "   ⚠️  DATABASE RESET ENABLED  ⚠️"
	bashio::log.warning "=================================================="
	bashio::log.warning "ALL DATA WILL BE PERMANENTLY DELETED!"
	bashio::log.warning "This includes:"
	bashio::log.warning "  - All tenant configurations and credentials"
	bashio::log.warning "  - All backups and snapshot archives"
	bashio::log.warning "  - All schedules and audit history"
	bashio::log.warning "=================================================="

	# Create timestamped backup before deleting
	BACKUP_DIR="/data/entramirror_backups"
	mkdir -p "$BACKUP_DIR"
	TIMESTAMP=$(date +%Y%m%d_%H%M%S)
	BACKUP_FILE="$BACKUP_DIR/entramirror_backup_${TIMESTAMP}.tar.gz"

	if [ -f "$DATA_DIR/entramirror.db" ] || [ -d "$SNAPSHOTS_DIR" ]; then
		bashio::log.info "Creating backup before data reset..."
		bashio::log.info "Backup location: $BACKUP_FILE"

		if tar -czf "$BACKUP_FILE" -C "$DATA_DIR" entramirror.db snapshots secrets 2>/dev/null; then
			bashio::log.info "Backup created successfully: $BACKUP_FILE"
		else
			bashio::log.warning "Backup failed, continuing with reset..."
		fi
	else
		bashio::log.info "No existing data directory found, skipping backup..."
	fi

	# Wait 5 seconds to give user time to cancel
	bashio::log.warning "Starting reset in 5 seconds... (Stop App NOW to abort)"
	sleep 5

	bashio::log.info "Proceeding with database reset..."

	# Delete database and secrets
	rm -f "$DATA_DIR/entramirror.db" "$DATA_DIR/entramirror.sqlite" 2>/dev/null || true
	rm -rf "${SECRETS_DIR:?}"/* 2>/dev/null || true
	rm -rf "${SNAPSHOTS_DIR:?}"/* 2>/dev/null || true
	sync

	bashio::log.info "=================================================="
	bashio::log.info "   ✅ DATABASE RESET COMPLETE"
	bashio::log.info "=================================================="
	bashio::log.info "All data has been deleted."
	bashio::log.info "The App will now restart with a fresh database."
	bashio::log.info ""
	bashio::log.warning "IMPORTANT: Disable 'reset_database' and 'reset_database_confirm' in the App settings!"
	bashio::log.warning "Otherwise, the database will be wiped again on next restart."
	bashio::log.info "=================================================="

	if bashio::app.option 'reset_database' && bashio::app.option 'reset_database_confirm'; then
		bashio::log.info "Database reset flags successfully cleared."
	else
		bashio::log.error "Failed to clear database reset flags! Loop may occur."
	fi
fi

# --- CREATE DATA DIRECTORIES ---
mkdir -p "$SNAPSHOTS_DIR"
mkdir -p "$SECRETS_DIR"

# --- READ CONFIGURATION FROM HA UI ---
bashio::log.info "Reading configuration from Home Assistant..."

# Version
VERSION=$(bashio::config 'version' | xargs)
bashio::log.info "Target Version: $VERSION"

# Log Level
if bashio::config.has_value 'log_level'; then
	LOG_LEVEL=$(bashio::config 'log_level')
	LOG_LEVEL=$(echo "$LOG_LEVEL" | tr '[:lower:]' '[:upper:]')
	case "$LOG_LEVEL" in
	TRACE | DEBUG) LOG_LEVEL="DEBUG" ;;
	INFO | NOTICE) LOG_LEVEL="INFO" ;;
	WARNING | WARN) LOG_LEVEL="WARNING" ;;
	ERROR | FATAL) LOG_LEVEL="ERROR" ;;
	*) LOG_LEVEL="INFO" ;;
	esac
	export LOG_LEVEL
	bashio::log.info "Log level set to: $LOG_LEVEL"
fi

# Database URL
export ENTRAMIRROR_DATABASE_URL="sqlite+aiosqlite:////data/entramirror.db"

# Secret Key
if bashio::config.has_value 'secret_key' && [ -n "$(bashio::config 'secret_key')" ]; then
	SECRET_KEY=$(bashio::config 'secret_key')
	export ENTRAMIRROR_SECRET_KEY="$SECRET_KEY"
	bashio::log.info "Using configured secret key"
else
	if [ ! -f "$DATA_DIR/.secret_key" ]; then
		bashio::log.info "Generating secret key..."
		python3 -c 'import secrets; print(secrets.token_urlsafe(32))' >"$DATA_DIR/.secret_key"
	fi
	SECRET_KEY=$(cat "$DATA_DIR/.secret_key")
	export ENTRAMIRROR_SECRET_KEY="$SECRET_KEY"
	bashio::log.info "Using auto-generated secret key"
fi

# Debug Mode
if bashio::config.true 'debug'; then
	export DEBUG="true"
	bashio::log.info "Debug mode: ENABLED"
else
	export DEBUG="false"
fi

# SSO Configuration
if bashio::config.true 'sso_enabled'; then
	export ENTRAMIRROR_SSO_ENABLED="true"
	if bashio::config.has_value 'sso_client_id'; then
		export ENTRAMIRROR_SSO_CLIENT_ID=$(bashio::config 'sso_client_id')
	fi
	if bashio::config.has_value 'sso_tenant_id'; then
		export ENTRAMIRROR_SSO_TENANT_ID=$(bashio::config 'sso_tenant_id')
	fi
	bashio::log.info "SSO Mode: ENABLED (Tenant: ${ENTRAMIRROR_SSO_TENANT_ID:-common})"
else
	export ENTRAMIRROR_SSO_ENABLED="false"
fi

# First Admin Password (if provided)
if bashio::config.has_value 'first_admin_password'; then
	FIRST_ADMIN_PASSWORD=$(bashio::config 'first_admin_password')
	export ENTRAMIRROR_FIRST_ADMIN_PASSWORD="$FIRST_ADMIN_PASSWORD"
fi

# GitHub Repo Configuration
if bashio::config.has_value 'github_repo' && [ -n "$(bashio::config 'github_repo')" ]; then
	GITHUB_REPO=$(bashio::config 'github_repo' | xargs)
	export GITHUB_REPO
	bashio::log.info "GitHub Repo set to: $GITHUB_REPO"
else
	export GITHUB_REPO="FaserF/EntraMirror"
	bashio::log.info "Using default GitHub Repo: $GITHUB_REPO"
fi

# Version Information
export APP_VERSION="${BUILD_VERSION:-0.1.0-dev}"

# --- HELPER FUNCTIONS FOR DOWNLOAD ---

get_auth_header() {
	local token="$1"
	if [[ -z "$token" ]]; then
		echo ""
	elif [[ "$token" == github_pat_* ]]; then
		echo "Authorization: Bearer $token"
	elif [[ "$token" == ghp_* ]]; then
		echo "Authorization: token $token"
	else
		echo "Authorization: Bearer $token"
	fi
}

download_file() {
	local url="$1"
	local output="$2"
	local token="$3"

	bashio::log.info "Attempting download from: $url"

	# 1. Try Public Access (No Token)
	bashio::log.debug "Trying public access..."
	if curl -L -f -H "Accept: application/vnd.github.v3+json" "$url" -o "$output" 2>/dev/null; then
		bashio::log.info "✅ Public download successful."
		return 0
	fi

	# 2. If failed, retry with token if available
	bashio::log.info "Public access failed. Checking for token..."

	if [ -n "$token" ]; then
		local auth_header
		auth_header=$(get_auth_header "$token")
		bashio::log.info "Token found (length: ${#token}). Retrying with authentication..."

		local http_code
		http_code=$(curl -L -w "%{http_code}" -H "$auth_header" -H "Accept: application/vnd.github.v3+json" "$url" -o "$output" 2>/dev/null)
		if [ "$http_code" = "200" ]; then
			bashio::log.info "✅ Authenticated download successful."
			return 0
		fi
		bashio::log.warning "API download returned HTTP $http_code"

		local direct_url
		direct_url=$(echo "$url" | sed 's|api.github.com/repos/|github.com/|' | sed 's|/tarball/|/archive/|')
		direct_url="${direct_url}.tar.gz"
		bashio::log.info "Trying direct archive URL: $direct_url"

		http_code=$(curl -L -w "%{http_code}" -H "$auth_header" "$direct_url" -o "$output" 2>/dev/null)
		if [ "$http_code" = "200" ]; then
			bashio::log.info "✅ Direct archive download successful."
			return 0
		fi
		bashio::log.warning "Direct download returned HTTP $http_code"

		bashio::log.error "❌ Download failed even with token."
		bashio::log.error "Please ensure your token has 'repo' scope for private repositories."
		return 1
	else
		bashio::log.error "❌ Public access failed and no 'github_token' is configured."
		bashio::log.error "If this is a private repository, please add a token in the configuration."
		return 1
	fi
}

install_from_archive() {
	local archive_path="$1"
	local extract_dir="$2"

	bashio::log.info "Extracting archive..."
	rm -rf "$extract_dir"
	mkdir -p "$extract_dir"

	local ARCHIVE_ROOT
	ARCHIVE_ROOT=$(tar -tzf "$archive_path" | head -1 | cut -d'/' -f1 2>/dev/null || echo "")
	local DETECTED_SHA=""
	if [ -n "$ARCHIVE_ROOT" ]; then
		DETECTED_SHA=$(echo "$ARCHIVE_ROOT" | awk -F'-' '{print $NF}' | cut -c1-7)
	fi

	tar -xzf "$archive_path" -C "$extract_dir" --strip-components=1

	local BASE_VERSION="0.1.0"
	if [ -f "$extract_dir/VERSION" ]; then
		BASE_VERSION=$(tr -d '\r\n' <"$extract_dir/VERSION")
		cp "$extract_dir/VERSION" /app/VERSION 2>/dev/null || true
	fi

	local CALCULATED_VERSION="$BASE_VERSION"
	if [ -n "$DETECTED_SHA" ]; then
		echo "$DETECTED_SHA" >/app/.git_commit 2>/dev/null || true
		export GIT_COMMIT="$DETECTED_SHA"
		export VITE_GIT_COMMIT="$DETECTED_SHA"
		if [[ "$BASE_VERSION" != *"-"* ]] && [[ "$BASE_VERSION" != *"b"* ]]; then
			CALCULATED_VERSION="${BASE_VERSION}-dev0+${DETECTED_SHA}"
		else
			CALCULATED_VERSION="${BASE_VERSION}+${DETECTED_SHA}"
		fi
	fi
	export APP_VERSION="$CALCULATED_VERSION"
	export VITE_APP_VERSION="$CALCULATED_VERSION"
	bashio::log.info "Resolved EntraMirror Core Version: $CALCULATED_VERSION (Commit: ${DETECTED_SHA:-unknown})"

	# Install Backend
	bashio::log.info "Installing Backend..."
	if [ -d "$extract_dir/backend" ]; then
		cp -r "$extract_dir/backend/"* /app/backend/

		if [ -f "/app/backend/requirements.txt" ]; then
			bashio::log.info "Installing Python dependencies from requirements.txt..."
			pip3 install --no-cache-dir -r /app/backend/requirements.txt ||
				bashio::log.warning "Some Python dependencies failed to install"
		fi
	else
		bashio::log.error "Backend directory not found in repository!"
		return 1
	fi

	# Build Docs
	if [ -f "$extract_dir/mkdocs.yml" ]; then
		bashio::log.info "Building MkDocs documentation..."
		cd "$extract_dir"
		mkdir -p /app/docs
		mkdocs build -f mkdocs.yml -d /app/docs || bashio::log.warning "MkDocs build failed, continuing..."
	fi

	# Build Frontend
	bashio::log.info "Building Frontend (this may take several minutes)..."
	if [ -d "$extract_dir/frontend" ]; then
		cd "$extract_dir/frontend" || return 1

		bashio::log.info "Running 'npm install'..."
		if npm install --legacy-peer-deps; then
			bashio::log.info "Running 'npm run build' with VITE_APP_VERSION=$VITE_APP_VERSION..."
			if VITE_APP_VERSION="$CALCULATED_VERSION" VITE_GIT_COMMIT="$DETECTED_SHA" npm run build; then
				bashio::log.info "Frontend build successful. Installing..."
				if [ -d "dist" ]; then
					rm -rf /app/frontend/*
					cp -r dist/* /app/frontend/
				else
					bashio::log.error "'dist' directory not found after build!"
					return 1
				fi
			else
				bashio::log.error "Frontend build failed!"
				return 1
			fi
		else
			bashio::log.error "npm install failed!"
			return 1
		fi
	else
		bashio::log.error "Frontend directory not found in repository!"
		return 1
	fi

	# Cleanup extraction dir
	cd / || return 1
	rm -rf "$extract_dir"
	return 0
}

# --- INITIAL CODE DOWNLOAD ---
if [ ! -f "/app/backend/app/main.py" ] || [ ! -f "/app/frontend/index.html" ]; then
	bashio::log.info "==================================================="
	bashio::log.info "   📦 INITIAL CODE DOWNLOAD REQUIRED"
	bashio::log.info "==================================================="
	bashio::log.info "This is the first start or code is missing."
	bashio::log.info "Attempting to download EntraMirror core..."

	GITHUB_TOKEN=""
	if bashio::config.has_value 'github_token'; then
		TOKEN_VALUE=$(bashio::config 'github_token')
		TOKEN_VALUE=$(echo "$TOKEN_VALUE" | xargs)
		if [ -n "$TOKEN_VALUE" ] && [ "$TOKEN_VALUE" != "null" ]; then
			GITHUB_TOKEN="$TOKEN_VALUE"
			bashio::log.info "✅ GitHub Token is configured (length: ${#GITHUB_TOKEN} chars)."
		else
			bashio::log.info "ℹ️ GitHub Token field is empty or null."
		fi
	else
		bashio::log.info "ℹ️ No GitHub Token configured."
	fi

	DOWNLOAD_VERSION="$VERSION"
	GITHUB_REPO_CONFIG="${GITHUB_REPO:-FaserF/EntraMirror}"

	if [ "$DOWNLOAD_VERSION" = "latest" ]; then
		bashio::log.info "Fetching latest release information for $GITHUB_REPO_CONFIG..."
		LATEST_RELEASE_TAG=""

		bashio::log.info "1. Trying public GitHub API..."
		if curl -s -f -o /tmp/latest_release.json "https://api.github.com/repos/${GITHUB_REPO_CONFIG}/releases/latest"; then
			bashio::log.info "✅ Public API request successful."
			LATEST_RELEASE_TAG=$(grep '"tag_name":' /tmp/latest_release.json | sed -E 's/.*"tag_name": "([^"]+)".*/\1/')
		else
			bashio::log.info "⚠️ Public API request failed (likely 404/403 or private repo)."
			if [ -n "$GITHUB_TOKEN" ]; then
				bashio::log.info "2. Retrying with provided GitHub Token (${#GITHUB_TOKEN} chars)..."
				AUTH_HEADER=$(get_auth_header "$GITHUB_TOKEN")
				if curl -s -f -H "$AUTH_HEADER" -o /tmp/latest_release.json "https://api.github.com/repos/${GITHUB_REPO_CONFIG}/releases/latest"; then
					bashio::log.info "✅ Authenticated API request successful."
					LATEST_RELEASE_TAG=$(grep '"tag_name":' /tmp/latest_release.json | sed -E 's/.*"tag_name": "([^"]+)".*/\1/')
				else
					bashio::log.warning "❌ Authenticated API request also failed. Please check your token permissions."
					bashio::log.warning "   Required scopes for private repos: 'repo' or 'contents:read'"
				fi
			else
				bashio::log.warning "⚠️ No GitHub Token available for authenticated retry."
				bashio::log.info "   If this is a private repository, please configure 'github_token'."
			fi
		fi

		rm -f /tmp/latest_release.json

		if [ -n "$LATEST_RELEASE_TAG" ]; then
			DOWNLOAD_VERSION="$LATEST_RELEASE_TAG"
			bashio::log.info "👉 Latest release identified: $DOWNLOAD_VERSION"
		else
			bashio::log.warning "⚠️ Could not identify latest release (or access denied)."
			bashio::log.warning "👉 Defaulting to 'main' branch as fallback."
			DOWNLOAD_VERSION="main"
		fi
	fi

	if [ "$DOWNLOAD_VERSION" = "main" ]; then
		DOWNLOAD_URL="https://api.github.com/repos/${GITHUB_REPO_CONFIG}/tarball/main"
	else
		DOWNLOAD_URL="https://api.github.com/repos/${GITHUB_REPO_CONFIG}/tarball/$DOWNLOAD_VERSION"
	fi

	bashio::log.info "Downloading version: $DOWNLOAD_VERSION"

	cd /tmp || exit 1
	if download_file "$DOWNLOAD_URL" "entramirror.tar.gz" "$GITHUB_TOKEN"; then
		if install_from_archive "entramirror.tar.gz" "/tmp/entramirror-src"; then
			rm -f /tmp/entramirror.tar.gz
			bashio::log.info "==================================================="
			bashio::log.info "   ✅ CODE DOWNLOAD COMPLETE"
			bashio::log.info "==================================================="
			INITIAL_DOWNLOAD_DONE="true"
		else
			bashio::log.error "Installation failed!"
			exit 1
		fi
	else
		bashio::log.error "Download failed! Please check your network or token settings."
		if [ "$VERSION" != "latest" ] && [ "$VERSION" != "main" ]; then
			bashio::log.warning "⚠️ Requested version '$VERSION' not available."
			bashio::log.warning "👉 Falling back to 'main' branch..."
			DOWNLOAD_URL="https://api.github.com/repos/${GITHUB_REPO_CONFIG}/tarball/main"
			if download_file "$DOWNLOAD_URL" "entramirror.tar.gz" "$GITHUB_TOKEN"; then
				bashio::log.info "✅ Fallback to main branch successful."
				if install_from_archive "entramirror.tar.gz" "/tmp/entramirror-src"; then
					rm -f /tmp/entramirror.tar.gz
					bashio::log.info "==================================================="
					bashio::log.info "   ✅ CODE DOWNLOAD COMPLETE (MAIN BRANCH)"
					bashio::log.info "==================================================="
					INITIAL_DOWNLOAD_DONE="true"
				else
					bashio::log.error "Installation failed during fallback!"
					exit 1
				fi
			else
				bashio::log.error "❌ Fallback to main branch also failed!"
				exit 1
			fi
		else
			exit 1
		fi
	fi
fi

# --- DEV MODE: USE MAIN BRANCH ---
if bashio::config.true 'developer_mode' && [ "${INITIAL_DOWNLOAD_DONE:-false}" != "true" ]; then
	bashio::log.warning "=================================================="
	bashio::log.warning "   ⚠️  DEVELOPER MODE ENABLED  ⚠️"
	bashio::log.warning "=================================================="
	bashio::log.warning "Using latest code from 'main' branch."
	bashio::log.warning "Downloading and rebuilding..."

	GITHUB_TOKEN=""
	if bashio::config.has_value 'github_token'; then
		TOKEN_VALUE=$(bashio::config 'github_token')
		TOKEN_VALUE=$(echo "$TOKEN_VALUE" | xargs)
		if [ -n "$TOKEN_VALUE" ] && [ "$TOKEN_VALUE" != "null" ]; then
			GITHUB_TOKEN="$TOKEN_VALUE"
		fi
	fi

	cd /tmp || exit 1
	GITHUB_REPO_CONFIG="${GITHUB_REPO:-FaserF/EntraMirror}"
	DOWNLOAD_URL="https://api.github.com/repos/${GITHUB_REPO_CONFIG}/tarball/main"

	if download_file "$DOWNLOAD_URL" "main.tar.gz" "$GITHUB_TOKEN"; then
		if install_from_archive "main.tar.gz" "/tmp/entramirror-main"; then
			rm -f /tmp/main.tar.gz
			bashio::log.info "=================================================="
			bashio::log.info "   ✅ DEV MODE UPDATE COMPLETE"
			bashio::log.info "=================================================="
		else
			bashio::log.error "Dev mode update failed!"
		fi
	else
		bashio::log.error "Failed to download main branch from GitHub!"
	fi
else
	bashio::log.info "Production Mode: Using existing/packaged version."
fi

# --- CREATE .ENV FILE FOR BACKEND ---
bashio::log.info "Creating .env file for backend..."
{
	echo "ENTRAMIRROR_SECRET_KEY=${ENTRAMIRROR_SECRET_KEY:-}"
	echo "ENTRAMIRROR_DATABASE_URL=sqlite+aiosqlite:////data/entramirror.db"
	echo "ENTRAMIRROR_DATA_DIR=/data"
	echo "ENTRAMIRROR_PORT=8001"
	echo "ENTRAMIRROR_LOG_LEVEL=${LOG_LEVEL:-INFO}"
	echo "ENTRAMIRROR_SSO_ENABLED=${ENTRAMIRROR_SSO_ENABLED:-false}"
	[ -n "${ENTRAMIRROR_SSO_CLIENT_ID:-}" ] && echo "ENTRAMIRROR_SSO_CLIENT_ID=${ENTRAMIRROR_SSO_CLIENT_ID}"
	[ -n "${ENTRAMIRROR_SSO_TENANT_ID:-}" ] && echo "ENTRAMIRROR_SSO_TENANT_ID=${ENTRAMIRROR_SSO_TENANT_ID}"
	[ -n "${ENTRAMIRROR_FIRST_ADMIN_PASSWORD:-}" ] && echo "ENTRAMIRROR_FIRST_ADMIN_PASSWORD=${ENTRAMIRROR_FIRST_ADMIN_PASSWORD}"
	echo "APP_VERSION=${APP_VERSION:-0.1.0-dev}"
	[ -n "${GIT_COMMIT:-}" ] && echo "GIT_COMMIT=${GIT_COMMIT}"
} >/app/backend/.env

# --- BACKEND START ---
bashio::log.info "Starting EntraMirror Backend (Uvicorn)..."
cd /app/backend || exit 1

export PYTHONPATH=/app/backend

# Ensure uvicorn is installed in Python environment
if ! python3 -c "import uvicorn" 2>/dev/null; then
	bashio::log.warning "uvicorn module not found in Python environment. Installing requirements..."
	if [ -f "/app/backend/requirements.txt" ]; then
		python3 -m pip install --no-cache-dir -r /app/backend/requirements.txt || true
	fi
fi

# Start Uvicorn in background on port 8001 (internal)
python3 -m uvicorn app.main:app --host 127.0.0.1 --port 8001 --proxy-headers --forwarded-allow-ips="*" --log-level "$(echo "$LOG_LEVEL" | tr '[:upper:]' '[:lower:]')" &
BACKEND_PID=$!

# --- NGINX START ---
bashio::log.info "Starting Nginx (Frontend & Docs)..."
mkdir -p /run/nginx
mkdir -p /var/lib/nginx/tmp/client_body /var/lib/nginx/tmp/proxy /var/lib/nginx/tmp/fastcgi /var/lib/nginx/tmp/uwsgi /var/lib/nginx/tmp/scgi
chown -R nginx:nginx /var/lib/nginx
nginx -g "daemon off;" &
NGINX_PID=$!

bashio::log.info "EntraMirror is now running!"
bashio::log.info "Access via Home Assistant Ingress"

# Trap signals to stop processes correctly
cleanup() {
	local exit_code=${1:-0}
	bashio::log.info "Shutting down services..."

	kill -TERM $NGINX_PID 2>/dev/null
	wait $NGINX_PID 2>/dev/null

	kill -TERM $BACKEND_PID 2>/dev/null
	wait $BACKEND_PID 2>/dev/null

	bashio::log.info "All services stopped"
	exit "$exit_code"
}

trap cleanup SIGTERM SIGHUP SIGINT

# Wait for any process to exit
wait -n $NGINX_PID $BACKEND_PID

if ! kill -0 "$NGINX_PID" 2>/dev/null; then
	bashio::log.error "Nginx exited unexpectedly!"
elif ! kill -0 "$BACKEND_PID" 2>/dev/null; then
	bashio::log.error "Backend service exited unexpectedly!"
else
	bashio::log.error "One of the services exited unexpectedly!"
fi
bashio::log.error "Stopping App..."
cleanup 1
