#!/usr/bin/with-contenv bashio
# shellcheck disable=SC2034,SC2129,SC2016
# shellcheck shell=bash

# <ADDON_BANNER_INJECTION>

# ============================================================================
# Addon Startup Banner - Auto-generated by CI
# ============================================================================
_show_startup_banner() {
    local VERSION="0.2.0"
    local NAME="Wiki.JS V3 (Beta)"
    local SLUG="wikijs3"
    local UNSUPPORTED="false"
    local REPO="FaserF/hassio-addons"
    local MAINTAINER="FaserF"

    # Extract base version and commit from dev versions (1.2.3-dev+abc123)
    local BASE_VERSION="${VERSION%%-dev*}"
    local DEV_COMMIT=""
    if [[ "$VERSION" == *"+""*" ]]; then
        DEV_COMMIT="${VERSION##*+}"
    fi

    # Header
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.blue "  🏠 $NAME"
    bashio::log.blue "  📦 Version: $VERSION"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Status indicator
    if [ "$UNSUPPORTED" = "true" ]; then
        bashio::log.error "🚨 STATUS: UNSUPPORTED"
        bashio::log.error "   This addon is no longer maintained!"
    elif [[ "$VERSION" == *"-dev"* ]]; then
        bashio::log.warning "🚧 STATUS: DEVELOPMENT"
        bashio::log.warning "   This is a development build!"
    elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
        bashio::log.notice "🔬 STATUS: BETA"
        bashio::log.notice "   This addon is in beta testing."
    else
        bashio::log.green "✅ STATUS: STABLE"
    fi

    # Helper for semantic version comparison
    version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }

    # ========================================================================
    # Smart Update Check
    # ========================================================================
    if command -v curl &>/dev/null; then
        local UPDATE_MSG=""

        # Get latest stable version from config.yaml
        local LATEST_STABLE
        LATEST_STABLE=$(curl -s --max-time 10 "https://raw.githubusercontent.com/$REPO/master/$SLUG/config.yaml" 2>/dev/null | grep -E "^version:" | head -1 | sed 's/version:[[:space:]]*["'"'"']\?\([^"'"'"'+]*\).*/\1/' | sed 's/-dev.*//')

        if [ -n "$LATEST_STABLE" ]; then
            # For DEV versions: Check if there are newer commits for this addon
            if [[ "$VERSION" == *"-dev"* ]]; then
                if [ -n "$DEV_COMMIT" ]; then
                    # Get latest commit for this addon from GitHub
                    local LATEST_COMMIT
                    LATEST_COMMIT=$(curl -s --max-time 10 "https://api.github.com/repos/$REPO/commits?path=$SLUG&per_page=1" 2>/dev/null | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4 | head -c7)

                    if [ -n "$LATEST_COMMIT" ] && [ "$LATEST_COMMIT" != "$DEV_COMMIT" ]; then
                        UPDATE_MSG="⬆️  DEV UPDATE: New commits available"
                        bashio::log.yellow "   Your commit: $DEV_COMMIT"
                        bashio::log.yellow "   Latest: $LATEST_COMMIT"
                    fi
                fi

                # Also check if a stable release is available
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # Compare versions
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                        bashio::log.yellow "   Consider upgrading to the stable release"
                    fi
                fi

            # For BETA versions (< 1.0.0): Check for newer beta OR stable
            elif [[ "${BASE_VERSION%%.*}" =~ ^[0-9]+$ ]] && [ "${BASE_VERSION%%.*}" -lt 1 ] 2>/dev/null; then
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    # If stable is >= 1.0.0, it's definitely newer
                    local LATEST_MAJOR="${LATEST_STABLE%%.*}"
                    if [ "$LATEST_MAJOR" -ge 1 ] 2>/dev/null; then
                        UPDATE_MSG="⬆️  STABLE RELEASE: $LATEST_STABLE available!"
                    elif version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi

            # For STABLE versions: Simple version comparison
            else
                if [ "$LATEST_STABLE" != "$BASE_VERSION" ]; then
                    if version_gt "$LATEST_STABLE" "$BASE_VERSION" 2>/dev/null; then
                        UPDATE_MSG="⬆️  UPDATE AVAILABLE: $LATEST_STABLE"
                    fi
                fi
            fi
        fi

        if [ -n "$UPDATE_MSG" ]; then
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            bashio::log.yellow "$UPDATE_MSG"
            bashio::log.yellow "   You are running: $VERSION"
            bashio::log.yellow "   Update via the Add-on Store"
            bashio::log.yellow "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        fi
    fi

    # Footer with links
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info "📝 Issues: https://github.com/$REPO/issues"
    bashio::log.info "💖 Maintained by: $MAINTAINER"
    bashio::log.blue "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info ""
}

# Show banner on startup
if type bashio::log.blue &>/dev/null 2>&1; then
    _show_startup_banner
fi

# </ADDON_BANNER_INJECTION>



# Enable strict mode
set -e
# shellcheck disable=SC1091

ssl=$(bashio::config 'ssl')
certfile=$(bashio::config 'certfile')
keyfile=$(bashio::config 'keyfile')
log_level=$(bashio::config 'log_level')

declare host
declare password
declare port
declare username

# SSL validation
if [ "$ssl" = "true" ]; then
	bashio::log.info "SSL is enabled. Validating certificates..."
	if [ ! -f "/ssl/$certfile" ]; then
		bashio::log.error "Cannot find certificate file $certfile. Turn off SSL or check if the file exists at /ssl/"
		exit 1
	fi
	if [ ! -f "/ssl/$keyfile" ]; then
		bashio::log.error "Cannot find certificate key file $keyfile. Turn off SSL or check if the file exists at /ssl/"
		exit 1
	fi
	bashio::log.info "SSL certificates validated."
fi

# Embedded PostgreSQL configuration
PGDATA="/data/postgresql"
host="localhost"
port="5432"
username="postgres"
password=$(bashio::config 'db_password')

bashio::log.info "Starting embedded PostgreSQL server..."

# Initialize PostgreSQL data directory if it doesn't exist
if [ ! -d "$PGDATA" ] || [ ! -f "$PGDATA/PG_VERSION" ]; then
	bashio::log.info "Initializing PostgreSQL database..."
	mkdir -p "$PGDATA"
	chown -R postgres:postgres "$PGDATA"
	chmod 700 "$PGDATA"
	su-exec postgres initdb -D "$PGDATA" --encoding=UTF8 --locale=C

	# Configure PostgreSQL for local connections
	echo "host all all 127.0.0.1/32 md5" >>"$PGDATA/pg_hba.conf"
	echo "listen_addresses = 'localhost'" >>"$PGDATA/postgresql.conf"
	bashio::log.info "PostgreSQL initialized successfully."
fi

# Ensure correct ownership
chown -R postgres:postgres "$PGDATA" /run/postgresql

# Start PostgreSQL server
bashio::log.info "Starting PostgreSQL server..."
touch /var/log/postgresql.log
chown postgres:postgres /var/log/postgresql.log
su-exec postgres pg_ctl -D "$PGDATA" -l /var/log/postgresql.log start

# Wait for PostgreSQL to be ready
bashio::log.info "Waiting for PostgreSQL to be ready..."
for i in {1..30}; do
	if su-exec postgres pg_isready -q; then
		break
	fi
	sleep 1
done

if ! su-exec postgres pg_isready -q; then
	bashio::log.error "PostgreSQL failed to start!"
	cat /var/log/postgresql.log
	exit 1
fi

bashio::log.info "PostgreSQL is ready!"

# Set postgres password if not already set
su-exec postgres psql -c "ALTER USER postgres WITH PASSWORD '${password}';" 2>/dev/null || true

#Drop database based on config flag (with safeguards)
if bashio::config.true 'reset_database'; then
	if ! bashio::config.true 'reset_database_confirm'; then
		bashio::log.error "Database reset requires both 'reset_database' and 'reset_database_confirm' to be enabled!"
		bashio::log.error "This is a DESTRUCTIVE operation that will DELETE ALL DATA!"
		bashio::log.error "Set 'reset_database_confirm: true' in your configuration to proceed."
		exit 1
	fi

	bashio::log.warning "=========================================="
	bashio::log.warning "WARNING: DESTRUCTIVE DATABASE OPERATION"
	bashio::log.warning "=========================================="
	bashio::log.warning "This will DROP the entire 'wiki' database!"
	bashio::log.warning "All data will be permanently lost!"
	bashio::log.warning "=========================================="

	# Create timestamped backup before dropping
	BACKUP_DIR="/config/backups"
	mkdir -p "$BACKUP_DIR"
	TIMESTAMP=$(date +%Y%m%d_%H%M%S)
	BACKUP_FILE="$BACKUP_DIR/wiki_backup_${TIMESTAMP}.sql"

	bashio::log.info "Creating backup before database reset..."
	bashio::log.info "Backup location: $BACKUP_FILE"

	# Create backup using pg_dump (using local socket connection)
	if su-exec postgres pg_dump wiki >"$BACKUP_FILE" 2>/dev/null; then
		bashio::log.info "Backup created successfully: $BACKUP_FILE"
	else
		bashio::log.warning "Backup failed (database may not exist yet), continuing with reset..."
	fi

	bashio::log.warning 'Recreating database (dropping existing if present)...'
	su-exec postgres psql -d postgres -c "DROP DATABASE IF EXISTS wiki;"

	#Remove reset_database options
	bashio::addon.option 'reset_database'
	bashio::addon.option 'reset_database_confirm'
fi

# Ensure /config directory exists
mkdir -p /config

# Generate configuration content once
CONFIG_CONTENT=$(
	cat <<EOF
port: 3000
db:
  type: postgres
  host: ${host}
  port: ${port}
  user: ${username}
  pass: ${password}
  db: wiki
  ssl: false
ssl:
  enabled: ${ssl}
  port: 3443
  provider: custom
  format: pem
  key: /ssl/${keyfile}
  cert: /ssl/${certfile}
pool:
bindIP: 0.0.0.0
logLevel: ${log_level}
offline: false
ha: false
dataPath: ./data
EOF
)

# Create Config file at the location Wiki.js expects
CONFIG_FILE="/config/wikijs-config.yml"
if [ ! -f "$CONFIG_FILE" ]; then
	bashio::log.info "Configuration file not found. Creating $CONFIG_FILE..."
	echo "$CONFIG_CONTENT" >"$CONFIG_FILE"
	bashio::log.info "Configuration file created successfully."
else
	bashio::log.info "Configuration file already exists at $CONFIG_FILE. Updating with current settings..."
	echo "$CONFIG_CONTENT" >"$CONFIG_FILE"
	bashio::log.info "Configuration file updated successfully."
fi

# Also create config.yml in /wiki for backward compatibility
echo "$CONFIG_CONTENT" >/wiki/config.yml

# Create database if not exists
su-exec postgres psql -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'wiki'" | grep -q 1 || su-exec postgres psql -d postgres -c "CREATE DATABASE wiki;"

# Enable pg_trgm extension (required for Wiki.js 3.0 search)
bashio::log.info "Ensuring 'pg_trgm' extension is enabled..."
su-exec postgres psql -d wiki -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"

echo "Starting Wiki.JS V3"
node server
